import {useEffect,useState} from 'react';
import {api} from './api';
import {Plus,Save,Trash2,RotateCcw} from 'lucide-react';

type Top={name:string;top_tvd_m:number;uncertainty_m:number;category:string;source:string;interpretation:string};
type Hole={name:string;top_md_m:number;bottom_md_m:number;diameter_m:number;source:string};
type Casing={name:string;top_md_m:number;bottom_md_m:number;outside_diameter_m:number;inside_diameter_m:number;minimum_wall_m:number;wall_loss_allowance_m:number;state:string;grade:string;source:string;yield_strength_pa:number|null;body_burst_pa:number|null;body_collapse_pa:number|null;body_tension_n:number|null;body_compression_n:number|null;connection_burst_pa:number|null;connection_collapse_pa:number|null;connection_tension_n:number|null;connection_compression_n:number|null;body_rating_source:string|null;connection_rating_source:string|null;cost_per_m:number|null;cost_currency:string|null;cost_basis:string|null};
type Geometry={survey_dataset_id:string;datum:string;coordinate_reference:string;wellhead_north_m:number;wellhead_east_m:number;wellhead_elevation_m:number;survey_quality_note:string;tool_to_bit_offset_m:number;formations:Top[];hole_sections:Hole[];casings:Casing[]};
type Point={md_m:number;north_m:number;east_m:number;tvd_m:number;elevation_m:number};
type Cross={name:string;category:string;top_tvd_m:number;uncertainty_m:number;top_crossings:Point[];coincident_intervals:{top_md_m:number;bottom_md_m:number}[];shallow_band_crossings:Point[];deep_band_crossings:Point[]};
export type Revision={id:string;sha256:string;created_at:string;input:Geometry;change_note:string;result:{samples:Point[];formation_intersections:Cross[];warnings:string[];assumptions:string[];cost:{status:string;value:number|null;currency:string|null;scope:string};total_depth_md_m:number}};
type Dataset={id:string;kind:string;filename:string;rows?:Record<string,number|string|null>[]};
type Project={id:string;datum:string;north_reference:string;origin:string;formations?:{name:string;top_tvd_m:number;uncertainty_m:number}[]};
type Props={project:Project;datasets:Dataset[];online:boolean;onError:(s:string)=>void;onNotice:(s:string)=>void;mode:'geometry'|'casing';onGeometryPage:()=>void};
const nf=(v:number|null|undefined,d=1)=>v==null?'—':v.toLocaleString('en-US',{maximumFractionDigits:d});
const ratingFields:[keyof Casing,string,number][]=[
  ['yield_strength_pa','Minimum yield strength (MPa)',1e6],['body_burst_pa','Body burst rating (MPa)',1e6],['body_collapse_pa','Body collapse rating (MPa)',1e6],['body_tension_n','Body tension rating (kN)',1000],['body_compression_n','Body compression rating (kN)',1000],
  ['connection_burst_pa','Connection burst rating (MPa)',1e6],['connection_collapse_pa','Connection collapse rating (MPa)',1e6],['connection_tension_n','Connection tension rating (kN)',1000],['connection_compression_n','Connection compression rating (kN)',1000]];
const emptyCasing=(name:string,td:number):Casing=>({name,top_md_m:0,bottom_md_m:td,outside_diameter_m:.244475,inside_diameter_m:.22,minimum_wall_m:.012,wall_loss_allowance_m:0,state:'planned',grade:'Unknown',source:'',yield_strength_pa:null,body_burst_pa:null,body_collapse_pa:null,body_tension_n:null,body_compression_n:null,connection_burst_pa:null,connection_collapse_pa:null,connection_tension_n:null,connection_compression_n:null,body_rating_source:null,connection_rating_source:null,cost_per_m:null,cost_currency:null,cost_basis:null});
function NumberField({label,value,onChange,factor=1,optional=false}:{label:string;value:number|null;onChange:(n:number|null)=>void;factor?:number;optional?:boolean}){
  return <label className="field-label">{label}<input type="number" step="any" required={!optional} value={value===null?'':value/factor} onChange={e=>onChange(e.target.value===''?null:Number(e.target.value)*factor)}/></label>;
}
function TextField({label,value,onChange,optional=false}:{label:string;value:string|null;onChange:(s:string)=>void;optional?:boolean}){
  return <label className="field-label">{label}<input required={!optional} value={value??''} maxLength={300} onChange={e=>onChange(e.target.value)}/></label>;
}

export function GeometryWorkspace({project,datasets,online,onError,onNotice,mode,onGeometryPage}:Props){
  const surveys=datasets.filter(d=>d.kind==='survey');
  const [revisions,setRevisions]=useState<Revision[]>([]),[saved,setSaved]=useState<Revision|null>(null),[draft,setDraft]=useState<Geometry|null>(null),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[note,setNote]=useState(''),[ready,setReady]=useState(false);
  const [surveySource,setSurveySource]=useState<Dataset|null>(null);
  const base='/projects/'+project.id;
  useEffect(()=>{let active=true;setSurveySource(null);if(draft?.survey_dataset_id)api<Dataset>(base+'/datasets/'+draft.survey_dataset_id).then(d=>{if(active)setSurveySource(d);}).catch(e=>{if(active)onError(e.message);});return()=>{active=false;};},[base,draft?.survey_dataset_id]);
  useEffect(()=>{let active=true;setReady(false);setSaved(null);setDraft(null);
    api<Revision[]>(base+'/engineering-revisions?module=M1').then(rs=>{if(!active)return;setRevisions(rs);setSaved(rs[0]??null);setDraft(rs[0]?.input??{survey_dataset_id:surveys[0]?.id??'',datum:project.datum,coordinate_reference:'Local project frame; no coordinate transformation',wellhead_north_m:0,wellhead_east_m:0,wellhead_elevation_m:0,survey_quality_note:'',tool_to_bit_offset_m:0,formations:[],hole_sections:[],casings:[]});setDirty(false);setReady(true);}).catch(e=>{if(active)onError(e.message);});
    return()=>{active=false;};
  },[project.id, datasets.map(d=>d.id).join(',')]);
  const update=(patch:Partial<Geometry>)=>{setDraft(v=>v?{...v,...patch}:v);setDirty(true);};
  if(!ready||!draft)return <div className="panel empty-inline">Loading engineering revisions…</div>;
  const activeSurvey=surveySource?.id===draft.survey_dataset_id?surveySource:null;
  const td=Number(activeSurvey?.rows?.at(-1)?.md_m??0);
  const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);onError('');try{
    const next=await api<Revision>(base+'/geometry',{method:'POST',body:JSON.stringify({base_revision_id:saved?.id??null,change_note:note,geometry:draft})});
    setSaved(next);setDraft(next.input);setRevisions(await api<Revision[]>(base+'/engineering-revisions?module=M1'));setDirty(false);setNote('');onNotice('Geometry revision saved. Earlier inputs and reports remain preserved.');
  }catch(e){onError((e as Error).message);}finally{setBusy(false);}};
  const example=()=>{if(project.origin!=='synthetic'||!td)return;
    const mid=td/2;const a=emptyCasing('Surface casing',mid),b=emptyCasing('Production casing',td);
    Object.assign(a,{outside_diameter_m:.339725,inside_diameter_m:.3135,minimum_wall_m:.013});
    for(const c of [a,b])Object.assign(c,{grade:'Synthetic test grade',source:'Generated geometry example; no manufacturer evidence',yield_strength_pa:552e6,body_burst_pa:55e6,body_collapse_pa:35e6,body_tension_n:2e6,body_compression_n:2e6,connection_burst_pa:50e6,connection_collapse_pa:30e6,connection_tension_n:1.8e6,connection_compression_n:1.8e6,body_rating_source:'Synthetic software test ratings; unqualified',connection_rating_source:'Synthetic software test connection ratings; unqualified',cost_per_m:100,cost_currency:'USD',cost_basis:'Synthetic illustrative pipe price'});
    update({survey_quality_note:'Synthetic survey for software verification',formations:(project.formations??[]).map(f=>({...f,category:'formation',source:'Synthetic demonstration interpretation',interpretation:'synthetic'})),hole_sections:[{name:'Upper hole',top_md_m:0,bottom_md_m:mid,diameter_m:.4445,source:'Synthetic demonstration geometry'},{name:'Lower hole',top_md_m:mid,bottom_md_m:td,diameter_m:.31115,source:'Synthetic demonstration geometry'}],casings:[a,b]});setNote('Synthetic geometry and casing example for software verification.');
  };
  return <div className="geometry-workspace">
    <div className="panel revision-banner"><div><h2>{mode==='geometry'?'Well Geometry & Stratigraphy':'Casing Programme & Structural Load Checks'}</h2><p>{saved?'Revision '+saved.id.slice(0,8)+' · '+new Date(saved.created_at).toUTCString():'No geometry revision saved yet.'}{dirty?' · Unsaved edits':''}</p></div><label className="field-label">Saved revision<select aria-label="Saved geometry revision" value={saved?.id??''} onChange={e=>{const r=revisions.find(r=>r.id===e.target.value);if(r){setSaved(r);setDraft(r.input);setDirty(false);setNote('');}}}><option value="" disabled>No saved revision</option>{revisions.map(r=><option key={r.id} value={r.id}>{r.id.slice(0,8)+' · '+r.change_note}</option>)}</select></label></div>
    {mode==='geometry'&&<div className="geometry-grid"><div className="panel"><div className="panel-heading"><div><h2>Survey path & interpreted surfaces</h2><p>Equal scale · local north/east · downward TVD · {project.north_reference} north</p></div></div>{saved?<Trajectory revision={saved}/>:<div className="empty-inline">Save a geometry revision to render its bound survey.</div>}{dirty&&<p className="inset-note">The view shows the saved revision. Save your edits to update it.</p>}</div><div className="panel"><div className="panel-heading"><div><h2>Formation intersections</h2><p>Horizontal interpreted surfaces; every crossing is retained.</p></div></div>{saved?<><div className="table-scroll"><table><thead><tr><th>Interpretation</th><th>Top TVD (m)</th><th>Pick band (m)</th><th>Crossing MD (m)</th></tr></thead><tbody>{saved.result.formation_intersections.map(f=><tr key={f.name}><td>{f.name}<small>{f.category}</small></td><td>{nf(f.top_tvd_m)}</td><td>±{nf(f.uncertainty_m)}</td><td>{[...f.top_crossings.map(p=>nf(p.md_m)),...(f.coincident_intervals??[]).map(r=>'Along surface: '+nf(r.top_md_m)+'–'+nf(r.bottom_md_m)+' m')].join(', ')||'No crossing'}</td></tr>)}</tbody></table></div><details className="inset-note"><summary>References, uncertainty & diagnostics</summary><p>{saved.input.coordinate_reference}</p><p>{saved.input.survey_quality_note}</p>{saved.result.assumptions.map(a=><p key={a}>{a}</p>)}{saved.result.warnings.map(w=><p key={w}>{w}</p>)}<code>SHA-256 {saved.sha256}</code></details></>:<div className="empty-inline">No interpreted surfaces saved.</div>}</div></div>}
    {mode==='casing'&&<><button className="text-button" onClick={onGeometryPage}>Edit survey, hole sections and formation references</button>{saved&&<CasingScenarios key={project.id+saved.id} base={base} revision={saved} disabled={dirty||!online} onError={onError} onNotice={onNotice}/>}</>}
    <form className="panel geometry-editor" onSubmit={save}><div className="panel-heading"><div><h2>{mode==='geometry'?'Engineering geometry editor':'Casing programme editor'}</h2><p>Inputs use metres, millimetres, MPa and kN as labelled. Sources and references are required.</p></div>{project.origin==='synthetic'&&<button type="button" className="button secondary" onClick={example}>Load synthetic example</button>}</div>
      {mode==='geometry'&&<><div className="lab-fields"><label className="field-label">Accepted survey<select value={draft.survey_dataset_id} required onChange={e=>update({survey_dataset_id:e.target.value})}><option value="">Select survey</option>{surveys.map(s=><option key={s.id} value={s.id}>{s.filename}</option>)}</select></label><TextField label="Fixed project depth datum" value={draft.datum} onChange={v=>update({datum:v})}/><TextField label="Coordinate frame / CRS and north basis" value={draft.coordinate_reference} onChange={v=>update({coordinate_reference:v})}/><TextField label="Survey quality and station-location basis" value={draft.survey_quality_note} onChange={v=>update({survey_quality_note:v})}/><NumberField label="Wellhead northing / local north (m)" value={draft.wellhead_north_m} onChange={v=>update({wellhead_north_m:v??0})}/><NumberField label="Wellhead easting / local east (m)" value={draft.wellhead_east_m} onChange={v=>update({wellhead_east_m:v??0})}/><NumberField label="Wellhead elevation, positive up (m)" value={draft.wellhead_elevation_m} onChange={v=>update({wellhead_elevation_m:v??0})}/><NumberField label="Tool-to-bit offset, metadata only (m)" value={draft.tool_to_bit_offset_m} onChange={v=>update({tool_to_bit_offset_m:v??0})}/></div>
      <div className="editor-section-heading"><h3>Interpreted formation tops</h3><button type="button" className="button secondary" onClick={()=>update({formations:[...draft.formations,{name:'',top_tvd_m:0,uncertainty_m:0,category:'formation',source:'',interpretation:project.origin==='synthetic'?'synthetic':'interpreted'}]})}><Plus size={15}/>Add top</button></div>
      {draft.formations.map((f,i)=>{const set=(p:Partial<Top>)=>update({formations:draft.formations.map((r,j)=>j===i?{...r,...p}:r)});return <div className="record-editor" key={i}><div className="lab-fields"><TextField label="Name" value={f.name} onChange={name=>set({name})}/><NumberField label="Top TVD (m)" value={f.top_tvd_m} onChange={v=>set({top_tvd_m:v??0})}/><NumberField label="Supplied top-pick uncertainty ±m" value={f.uncertainty_m} onChange={v=>set({uncertainty_m:v??0})}/><label className="field-label">Interpretation category<select value={f.category} onChange={e=>set({category:e.target.value})}>{['formation','aquifer','reactive','fault'].map(k=><option key={k}>{k}</option>)}</select></label><TextField label="Interpretation source / revision" value={f.source} onChange={source=>set({source})}/><label className="field-label">Evidence origin<select value={f.interpretation} onChange={e=>set({interpretation:e.target.value})}><option>interpreted</option><option>synthetic</option></select></label></div><button type="button" className="text-button" onClick={()=>update({formations:draft.formations.filter((_,j)=>j!==i)})}><Trash2 size={14}/>Remove draft top</button></div>;})}
      <div className="editor-section-heading"><h3>Hole sections · ordered, contiguous MD</h3><button type="button" className="button secondary" onClick={()=>update({hole_sections:[...draft.hole_sections,{name:'',top_md_m:draft.hole_sections.at(-1)?.bottom_md_m??0,bottom_md_m:td,diameter_m:.31115,source:''}]})}><Plus size={15}/>Add section</button></div>
      {draft.hole_sections.map((h,i)=>{const set=(p:Partial<Hole>)=>update({hole_sections:draft.hole_sections.map((r,j)=>j===i?{...r,...p}:r)});return <div className="record-editor" key={i}><div className="lab-fields"><TextField label="Section name" value={h.name} onChange={name=>set({name})}/><NumberField label="Top MD (m)" value={h.top_md_m} onChange={v=>set({top_md_m:v??0})}/><NumberField label="Bottom MD (m)" value={h.bottom_md_m} onChange={v=>set({bottom_md_m:v??0})}/><NumberField label="Hole diameter (mm)" value={h.diameter_m} factor={.001} onChange={v=>set({diameter_m:v??0})}/><TextField label="Geometry source" value={h.source} onChange={source=>set({source})}/></div><button type="button" className="text-button" onClick={()=>update({hole_sections:draft.hole_sections.filter((_,j)=>j!==i)})}><Trash2 size={14}/>Remove draft section</button></div>;})}</>}
      <div className="editor-section-heading"><h3>Casing & liner records</h3><button type="button" className="button secondary" onClick={()=>update({casings:[...draft.casings,emptyCasing('',td)]})}><Plus size={15}/>Add string</button></div>
      {draft.casings.map((c,i)=>{const set=(p:Partial<Casing>)=>update({casings:draft.casings.map((r,j)=>j===i?{...r,...p}:r)});return <div className="record-editor" key={i}><div className="lab-fields"><TextField label="Casing / liner name" value={c.name} onChange={name=>set({name})}/><label className="field-label">Record state<select value={c.state} onChange={e=>set({state:e.target.value})}><option>planned</option><option>installed</option></select></label><NumberField label="Top MD (m)" value={c.top_md_m} onChange={v=>set({top_md_m:v??0})}/><NumberField label="Shoe MD (m)" value={c.bottom_md_m} onChange={v=>set({bottom_md_m:v??0})}/><NumberField label="Outside diameter (mm)" value={c.outside_diameter_m} factor={.001} onChange={v=>set({outside_diameter_m:v??0})}/><NumberField label="Nominal inside diameter (mm)" value={c.inside_diameter_m} factor={.001} onChange={v=>set({inside_diameter_m:v??0})}/><NumberField label="Qualified minimum wall (mm)" value={c.minimum_wall_m} factor={.001} onChange={v=>set({minimum_wall_m:v??0})}/><NumberField label="Wall-loss allowance (mm)" value={c.wall_loss_allowance_m} factor={.001} onChange={v=>set({wall_loss_allowance_m:v??0})}/><TextField label="Grade / material" value={c.grade} onChange={grade=>set({grade})}/><TextField label="Component record source" value={c.source} onChange={source=>set({source})}/></div>
      <details><summary>Body, connection and cost evidence · blank ratings stay missing</summary><p className="small-note">Ratings must apply to the remaining wall, connection and service conditions. Supplied values are recorded evidence; this app does not certify them.</p><div className="lab-fields">{ratingFields.map(([key,label,factor])=><NumberField key={key} label={label} value={c[key] as number|null} factor={factor} optional onChange={v=>set({[key]:v})}/>)}<TextField label="Body rating / material evidence" value={c.body_rating_source} optional onChange={v=>set({body_rating_source:v||null})}/><TextField label="Connection rating evidence" value={c.connection_rating_source} optional onChange={v=>set({connection_rating_source:v||null})}/><NumberField label="Pipe cost per metre (optional)" value={c.cost_per_m} optional onChange={v=>set({cost_per_m:v})}/><TextField label="Currency code, e.g. USD" value={c.cost_currency} optional onChange={v=>set({cost_currency:v||null})}/><TextField label="Price basis and date" value={c.cost_basis} optional onChange={v=>set({cost_basis:v||null})}/></div></details><button type="button" className="text-button" onClick={()=>update({casings:draft.casings.filter((_,j)=>j!==i)})}><Trash2 size={14}/>Remove draft string</button></div>;})}
      {!draft.casings.length&&<p className="empty-inline">No casing records. Add a string to define its geometry and available evidence.</p>}
      <TextField label="Revision change note" value={note} onChange={setNote}/><div className="lab-action"><button className="button primary" disabled={busy||!online||!draft.survey_dataset_id}><Save size={16}/>{busy?'Saving…':'Save geometry revision'}</button><button type="button" className="button secondary" onClick={()=>{if(saved){setDraft(saved.input);setDirty(false);setNote('');}}} disabled={!saved}><RotateCcw size={15}/>Reset draft</button></div>
    </form>
  </div>;
}

function Trajectory({revision}:{revision:Revision}){
  const [view,setView]=useState<'3d'|'section'|'plan'>('3d'),[yaw,setYaw]=useState(45),[tilt,setTilt]=useState(25),[index,setIndex]=useState(0);
  const samples=revision.result.samples,g=revision.input;
  const project=(n:number,e:number,z:number):[number,number]=>{
    const a=yaw*Math.PI/180,b=tilt*Math.PI/180;
    const x=n*Math.cos(a)+e*Math.sin(a),y=-n*Math.sin(a)+e*Math.cos(a);
    return view==='plan'?[e,-n]:view==='section'?[x,z]:[x,z*Math.cos(b)-y*Math.sin(b)];
  };
  const extent=Math.max(50,...samples.map(p=>Math.hypot(p.north_m,p.east_m)))*1.05;
  const plane=(tvd:number)=>[[-extent,-extent],[extent,-extent],[extent,extent],[-extent,extent]].map(([n,e])=>project(n,e,tvd));
  const pp=samples.map(p=>project(p.north_m,p.east_m,p.tvd_m));
  const bounds=[...pp,...(view==='plan'?[]:g.formations.flatMap(f=>plane(f.top_tvd_m))),project(0,0,0)];
  const minx=Math.min(...bounds.map(p=>p[0])),maxx=Math.max(...bounds.map(p=>p[0])),miny=Math.min(...bounds.map(p=>p[1])),maxy=Math.max(...bounds.map(p=>p[1]));
  const scale=Math.min(560/Math.max(1,maxx-minx),370/Math.max(1,maxy-miny));
  const screen=(p:[number,number])=>[320+(p[0]-(minx+maxx)/2)*scale,215+(p[1]-(miny+maxy)/2)*scale];
  const point=(p:Point)=>screen(project(p.north_m,p.east_m,p.tvd_m)).join(',');
  const path=samples.map(point).join(' ');
  const axisSize=Math.max(revision.result.total_depth_md_m,extent)/5,origin=screen(project(0,0,0));
  const selected=samples[Math.min(index,samples.length-1)];
  return <div className="trajectory-view"><div className="well-controls"><div className="segmented">{(['3d','section','plan'] as const).map(v=><button type="button" key={v} className={view===v?'selected':''} onClick={()=>setView(v)}>{v==='3d'?'3D':v==='section'?'Section':'Plan'}</button>)}</div><span className="subtle">Orthographic · dimensions in metres</span></div>
    <svg viewBox="0 0 640 460" role="img" aria-label="Rotatable 3D survey trajectory with interpreted horizontal formation surfaces and schematic casing overlays">
      {view!=='plan'&&g.formations.map((f,i)=><g key={f.name}><polygon points={plane(f.top_tvd_m).map(p=>screen(p).join(',')).join(' ')} fill={['#d7e1bd','#bad6cd','#e4d5bc'][i%3]} stroke="#829b87" opacity=".35"/>{f.uncertainty_m>0&&[-1,1].map(sign=><polygon key={sign} points={plane(f.top_tvd_m+sign*f.uncertainty_m).map(p=>screen(p).join(',')).join(' ')} fill="#cab892" opacity=".12"/>)}<text x={screen(plane(f.top_tvd_m)[2])[0]} y={screen(plane(f.top_tvd_m)[2])[1]-4}>{f.name}</text></g>)}
      {g.hole_sections.map(h=><polyline key={h.name} points={samples.filter(p=>p.md_m>=h.top_md_m&&p.md_m<=h.bottom_md_m).map(point).join(' ')} fill="none" stroke="#b7c2bb" strokeWidth={Math.max(8,h.diameter_m*30)} opacity=".28"/>)}
      {[...g.casings].sort((a,b)=>b.outside_diameter_m-a.outside_diameter_m).map((c,i)=><polyline key={c.name} points={samples.filter(p=>p.md_m>=c.top_md_m&&p.md_m<=c.bottom_md_m).map(point).join(' ')} fill="none" stroke={['#c89c53','#809abb','#867eb7'][i%3]} strokeWidth={Math.max(5,c.outside_diameter_m*25)} opacity=".5"/>)}
      <polyline points={path} fill="none" stroke="#216f5d" strokeWidth="2.5"/>
      {([['N',axisSize,0,0],['E',0,axisSize,0],['TVD ↓',0,0,axisSize]] as const).map(([label,n,e,z])=>{const p=screen(project(n,e,z));return <g key={label}><line x1={origin[0]} y1={origin[1]} x2={p[0]} y2={p[1]} stroke="#58685e"/><text x={p[0]+5} y={p[1]}>{label}</text></g>;})}
      {selected&&<circle cx={screen(project(selected.north_m,selected.east_m,selected.tvd_m))[0]} cy={screen(project(selected.north_m,selected.east_m,selected.tvd_m))[1]} r="5" fill="#d4e9a8" stroke="#216f5d"/>}
      <text x="25" y="445">Hole/casing widths are schematic · formation bands use supplied pick uncertainty</text>
    </svg>
    {view!=='plan'&&<label className="angle-control">View azimuth<input aria-label="3D view azimuth" type="range" min="0" max="360" value={yaw} onChange={e=>setYaw(+e.target.value)}/><span>{yaw}°</span></label>}
    {view==='3d'&&<label className="angle-control">View tilt<input aria-label="3D view tilt" type="range" min="-80" max="80" value={tilt} onChange={e=>setTilt(+e.target.value)}/><span>{tilt}°</span></label>}
    <label className="angle-control">Inspect sampled MD<input aria-label="Inspect trajectory sample" type="range" min="0" max={samples.length-1} value={index} onChange={e=>setIndex(+e.target.value)}/><span>{nf(selected?.md_m)} m</span></label>
    {selected&&<p className="inset-note">MD {nf(selected.md_m)} m · TVD {nf(selected.tvd_m)} m · North {nf(selected.north_m)} m · East {nf(selected.east_m)} m · Elevation {nf(selected.elevation_m)} m</p>}
    <div className="geometry-legend">{g.casings.map((c,i)=><span key={c.name}><i style={{background:['#c89c53','#809abb','#867eb7'][i%3]}}/>{c.name} · {c.state}</span>)}</div>
  </div>;
}

type Load={name:string;casing_name:string;md_m:number;internal_gauge_pa:number;external_gauge_pa:number;axial_wall_force_n:number;source:string};
type Check={check:string;utilization:number|null;status:string;margin:number|null};
type LoadResult={casing:string;load_case:string;md_m:number;status:string;maximum_utilization:number|null;governing_check:string|null;stresses:{location:string;radial_pa:number;hoop_pa:number;axial_pa:number;von_mises_pa:number}[];checks:Check[]};
type CasingCalculation={id:string;created_at:string;inputs_si:Record<string,unknown>;result:{status:string;candidate_name:string;geometry_revision_id:string;checks:LoadResult[];missing_load_cases:{casing:string;load_case:string;reason:string}[];assumptions:string[]}};
function CasingScenarios({base,revision,disabled,onError,onNotice}:{base:string;revision:Revision;disabled:boolean;onError:(s:string)=>void;onNotice:(s:string)=>void}){
  const [catalog,setCatalog]=useState('circulation'),[loads,setLoads]=useState<Load[]>([]),[history,setHistory]=useState<CasingCalculation[]>([]),[result,setResult]=useState<CasingCalculation|null>(null),[busy,setBusy]=useState(false),[changed,setChanged]=useState(false);
  useEffect(()=>{api<CasingCalculation[]>(base+'/calculations?model=casing').then(setHistory).catch(e=>onError(e.message));},[base]);
  const generate=(synthetic=false)=>{const names=catalog.split(',').map(v=>v.trim()).filter(Boolean);setLoads(revision.input.casings.flatMap(c=>names.map(name=>({name,casing_name:c.name,md_m:c.bottom_md_m,internal_gauge_pa:synthetic?20e6:0,external_gauge_pa:synthetic?10e6:0,axial_wall_force_n:synthetic?400000:0,source:synthetic?'Synthetic software test load case':''}))));setChanged(true);};
  return <div className="panel casing-scenarios"><div className="panel-heading"><div><h2>Candidate load-case comparison</h2><p>Bound to geometry {revision.id.slice(0,8)}. Positive force is total axial wall tension, including applicable pressure-end loads.</p></div></div>
    <form onChange={()=>setChanged(true)} onSubmit={async e=>{e.preventDefault();setBusy(true);onError('');try{const f=new FormData(e.currentTarget);const data={geometry_revision_id:revision.id,candidate_name:f.get('candidate'),required_load_cases:catalog.split(',').map(v=>v.trim()).filter(Boolean),loads,yield_factor:Number(f.get('yield_factor')),burst_factor:Number(f.get('burst_factor')),collapse_factor:Number(f.get('collapse_factor')),axial_factor:Number(f.get('axial_factor')),factor_basis:f.get('factor_basis'),temperature_derating:Number(f.get('temperature_derating')),derating_basis:f.get('derating_basis')};const value=await api<CasingCalculation>(base+'/calculations/casing',{method:'POST',body:JSON.stringify(data)});setResult(value);setChanged(false);setHistory(await api<CasingCalculation[]>(base+'/calculations?model=casing'));onNotice('Casing scenario and all supplied load/rating evidence saved.');}catch(e){onError((e as Error).message);}finally{setBusy(false);}}}>
      <div className="lab-fields"><label className="field-label">Candidate name<input name="candidate" required maxLength={100} placeholder="e.g. Programme A / circulation review"/></label><label className="field-label">Mandatory case catalogue, comma-separated<input value={catalog} onChange={e=>setCatalog(e.target.value)} required/></label>{['yield','burst','collapse','axial'].map(k=><label className="field-label" key={k}>{k.charAt(0).toUpperCase()+k.slice(1)} design factor<input name={k+'_factor'} type="number" min="1" max="10" step="any" defaultValue="1.25" required/></label>)}<label className="field-label">Factor basis / approval reference<input name="factor_basis" required minLength={3} maxLength={300} placeholder="Declare the study's factor basis"/></label><label className="field-label">Supplied temperature derating, 0–1<input name="temperature_derating" type="number" min=".001" max="1" step="any" defaultValue="1" required/></label><label className="field-label">Derating basis and service envelope<input name="derating_basis" required minLength={3} maxLength={300} placeholder="State the evidence behind this factor"/></label></div>
      <div className="editor-section-heading"><h3>Loads at explicit MD</h3><button type="button" className="button secondary" onClick={()=>generate(false)} disabled={!revision.input.casings.length}><Plus size={15}/>Generate catalogue rows</button></div>
      <p className="small-note">Generate rows for every casing and mandatory case, then enter the study loads and their sources. This is a restricted elastic/rating screen. Factors shown initially are editable study inputs.</p>
      {loads.map((l,i)=>{const set=(patch:Partial<Load>)=>{setLoads(v=>v.map((r,j)=>i===j?{...r,...patch}:r));setChanged(true);};return <div className="record-editor" key={i}><h4>{l.casing_name+' · '+l.name}</h4><div className="lab-fields"><NumberField label="Load location MD (m)" value={l.md_m} onChange={v=>set({md_m:v??0})}/><NumberField label="Internal pressure (MPa gauge)" value={l.internal_gauge_pa} factor={1e6} onChange={v=>set({internal_gauge_pa:v??0})}/><NumberField label="External pressure (MPa gauge)" value={l.external_gauge_pa} factor={1e6} onChange={v=>set({external_gauge_pa:v??0})}/><NumberField label="Total wall force, tension positive (kN)" value={l.axial_wall_force_n} factor={1000} onChange={v=>set({axial_wall_force_n:v??0})}/><TextField label="Load source / scenario basis" value={l.source} onChange={source=>set({source})}/></div><button type="button" className="text-button" onClick={()=>{setLoads(v=>v.filter((_,j)=>i!==j));setChanged(true);}}><Trash2 size={14}/>Remove draft load</button></div>;})}
      <div className="lab-action"><button className="button primary" disabled={busy||disabled||!loads.length}>{busy?'Calculating…':'Check & save scenario'}</button><span className="small-note">{disabled?'Save geometry edits before calculating.':''}</span></div>
    </form>
    {result&&<div className="casing-result"><h3>{result.result.candidate_name} <span className={'badge '+(result.result.status==='conditional'?'green':'amber')}>{result.result.status.replaceAll('_',' ')}</span></h3>{changed&&<p className="inset-note">Inputs have changed. This result retains the previously saved inputs.</p>}<p>Geometry revision {result.result.geometry_revision_id.slice(0,8)} · No design approval is issued.</p><details className="inset-note"><summary>Preserved inputs for this result</summary><pre>{JSON.stringify(result.inputs_si,null,2)}</pre></details><div className="table-scroll"><table><thead><tr><th>Casing / case</th><th>MD (m)</th><th>Governing screen</th><th>Utilization</th><th>Evidence state</th><th/></tr></thead><tbody>{result.result.checks.map((r,i)=><tr key={i}><td>{r.casing+' / '+r.load_case}</td><td>{nf(r.md_m)}</td><td>{r.governing_check?.replaceAll('_',' ')}</td><td>{r.maximum_utilization===null?'—':nf(r.maximum_utilization*100)+'%'}</td><td>{r.status.replaceAll('_',' ')}</td><td><details><summary>All screens & stresses</summary><table><thead><tr><th>Screen</th><th>Utilization</th><th>State</th></tr></thead><tbody>{r.checks.map(c=><tr key={c.check}><td>{c.check.replaceAll('_',' ')}</td><td>{c.utilization===null?'Missing rating':nf(c.utilization*100)+'%'}</td><td>{c.status.replaceAll('_',' ')}</td></tr>)}</tbody></table><table><thead><tr><th>Wall location</th><th>Radial MPa</th><th>Hoop MPa</th><th>Axial MPa</th><th>VM MPa</th></tr></thead><tbody>{r.stresses.map(s=><tr key={s.location}><td>{s.location}</td><td>{nf(s.radial_pa/1e6)}</td><td>{nf(s.hoop_pa/1e6)}</td><td>{nf(s.axial_pa/1e6)}</td><td>{nf(s.von_mises_pa/1e6)}</td></tr>)}</tbody></table></details></td></tr>)}</tbody></table></div>{result.result.missing_load_cases.map((m,i)=><p className="inset-note" key={i}>{m.casing+' / '+m.load_case+': '+m.reason}</p>)}<details className="inset-note"><summary>Model assumptions and exclusions</summary>{result.result.assumptions.map(a=><p key={a}>{a}</p>)}</details></div>}
    <div className="editor-section-heading"><h3>Preserved candidate comparisons</h3></div><p className="small-note">Compare only equivalent load catalogues and factor bases; each entry preserves its own geometry and inputs.</p><div className="table-scroll"><table><thead><tr><th>Candidate</th><th>Geometry</th><th>Maximum utilization</th><th>State</th><th/></tr></thead><tbody>{history.map(h=><tr key={h.id}><td>{h.result.candidate_name}</td><td>{h.result.geometry_revision_id.slice(0,8)}</td><td>{h.result.checks.some(c=>c.maximum_utilization!==null)?nf(Math.max(...h.result.checks.map(c=>c.maximum_utilization??0))*100)+'%':'Missing ratings'}</td><td>{h.result.status.replaceAll('_',' ')}</td><td><button type="button" className="text-button" onClick={()=>{setResult(h);setChanged(true);}}>Open saved result</button></td></tr>)}</tbody></table></div><p className="inset-note">Pipe-length cost: {revision.result.cost.value===null?'Insufficient cost evidence':nf(revision.result.cost.value,0)+' '+revision.result.cost.currency+'. '+revision.result.cost.scope}</p>
  </div>;
}
