import {useEffect,useRef,useState} from 'react';
import {engineeringApi,scopeQuery,type EngineeringScope} from './api';
import {CalculationFreshness} from './CalculationFreshness';
import type {Revision} from './GeometryWorkspace';

type StringSection={name:string;top_md_m:number;bottom_md_m:number;outside_diameter_m:number;inside_diameter_m:number;source_note:string};
type Knot={md_m:number;pore_gauge_pa:number;fracture_gauge_pa:number;pore_upper_allowance_pa:number;fracture_lower_allowance_pa:number};
type Input={study_name:string;geometry_revision_id:string;depth_datum:string;scenario_at:string;maximum_mud_age_hours:number;
  mud:{density_kg_m3:number;rheology:string;consistency_pa_sn:number;flow_index:number;yield_stress_pa:number;measured_at:string;evidence_state:string;source_note:string;test_temperature_c:number;density_rheology_basis_note:string};
  circulation_state:string;flow_regime:string;applicability_note:string;geometry_state:string;string_sections:StringSection[];
  flow_m3_s:number;surface_backpressure_pa:number;surface_loss_pa:number;surface_loss_note:string;nozzle_total_area_m2:number;nozzle_discharge_coefficient:number;nozzle_source_note:string;
  rotation_rad_s:number;eccentricity_fraction:number;cuttings_volume_fraction:number;wall_roughness_m:number;
  pressure_window:{reference:string;interpolation:string;evidence_state:string;source_note:string;review_note:string;knots:Knot[]};
  surface_rating_pa:number|null;surface_rating_source:string|null;
  sensitivity:{density_delta_kg_m3:number;flow_delta_m3_s:number;consistency_relative_delta:number;backpressure_delta_pa:number}};
type Point={md_m:number;tvd_m:number;static_gauge_pa:number;annular_gauge_pa:number;pipe_gauge_pa:number;lower_assessed_pa:number;upper_assessed_pa:number;above_pore_allowance_pa:number;below_fracture_allowance_pa:number;tested_min_gauge_pa:number|null;tested_max_gauge_pa:number|null;equivalent_density_including_backpressure_kg_m3:number|null};
type Segment={top_md_m:number;bottom_md_m:number;bore_source:string;bore_diameter_m:number;string_name:string;annular_velocity_m_s:number;pipe_velocity_m_s:number;annular_loss_pa:number;pipe_loss_pa:number;annular_re_screen:number;pipe_re_screen:number;annular:Record<string,number>;pipe:Record<string,number>};
type Minimum={margin_pa:number;md_m:number;tvd_m:number;parameters:Record<string,number>};
type Study={id:string;created_at:string;inputs_si:Input;result:{status:string;mud_age_hours:number;reasons:string[];warnings:string[];approval_issued:boolean;geometry_sha256:string;survey_source_sha256:string;within_all_tested_bounds:boolean;profile:Point[];
  nominal:null|{annular_loss_pa:number;pipe_loss_pa:number;bit_loss_pa:number;surface_loss_pa:number;standpipe_gauge_pa:number;required_supply_gauge_pa:number;segments:Segment[];numerical_loss_change_indicator_pa:number;bottom_path_balance_residual_pa:number;mass_in_kg_s:number;mass_out_kg_s:number};
  sensitivity:null|{tested_admissible_corners:number;tested_withheld_corners:Record<string,unknown>[];minimum_above_pore:Minimum;minimum_below_fracture:Minimum;cases:unknown[]};
  surface_equipment?:{maximum_tested_supply_pa:number;supplied_rating_pa:number|null;margin_pa:number|null;rating_source:string|null}}};
type Props=EngineeringScope & {project:{id:string;datum:string;origin:string};online:boolean;onError:(s:string)=>void;onNotice:(s:string)=>void};
const fmt=(v:number|null|undefined,d=3)=>v==null?'—':(Math.abs(v)<.5*10**(-d)?0:v).toLocaleString('en-US',{maximumFractionDigits:d});
function initial(project:Props['project'],revision?:Revision):Input{
  const td=revision?.result.total_depth_md_m??1000;
  return {study_name:'',geometry_revision_id:revision?.id??'',depth_datum:project.datum,scenario_at:new Date().toISOString(),maximum_mud_age_hours:24,
    mud:{density_kg_m3:1200,rheology:'herschel_bulkley',consistency_pa_sn:.2,flow_index:.7,yield_stress_pa:3,measured_at:'',evidence_state:'unknown',source_note:'',test_temperature_c:20,density_rheology_basis_note:''},
    circulation_state:'unknown',flow_regime:'unknown',applicability_note:'',geometry_state:'installed_only',
    string_sections:[{name:'String section',top_md_m:0,bottom_md_m:td,outside_diameter_m:.127,inside_diameter_m:.108,source_note:''}],
    flow_m3_s:.001,surface_backpressure_pa:0,surface_loss_pa:0,surface_loss_note:'',nozzle_total_area_m2:.0003,nozzle_discharge_coefficient:.95,nozzle_source_note:'',
    rotation_rad_s:0,eccentricity_fraction:0,cuttings_volume_fraction:0,wall_roughness_m:0,
    pressure_window:{reference:'surface_atmospheric_gauge',interpolation:'piecewise_linear_md',evidence_state:'unreviewed',source_note:'',review_note:'',
      knots:[{md_m:0,pore_gauge_pa:0,fracture_gauge_pa:1e6,pore_upper_allowance_pa:0,fracture_lower_allowance_pa:0},{md_m:td,pore_gauge_pa:0,fracture_gauge_pa:1e6,pore_upper_allowance_pa:0,fracture_lower_allowance_pa:0}]},
    surface_rating_pa:null,surface_rating_source:null,sensitivity:{density_delta_kg_m3:0,flow_delta_m3_s:0,consistency_relative_delta:0,backpressure_delta_pa:0}};
}
function NumberField({label,value,onChange,factor=1,min,max,optional=false}:{label:string;value:number|null;onChange:(v:number|null)=>void;factor?:number;min?:number;max?:number;optional?:boolean}){
  return <label className="field-label">{label}<input type="number" step="any" required={!optional} min={min} max={max} value={value===null||!Number.isFinite(value)?'':value/factor} onChange={e=>onChange(e.target.value===''?(optional?null:NaN):Number(e.target.value)*factor)}/></label>;
}
function TextField({label,value,onChange,optional=false}:{label:string;value:string|null;onChange:(v:string)=>void;optional?:boolean}){
  return <label className="field-label">{label}<textarea required={!optional} minLength={optional?0:3} maxLength={700} value={value??''} onChange={e=>onChange(e.target.value)}/></label>;
}
function SelectField({label,value,options,onChange}:{label:string;value:string;options:[string,string][];onChange:(v:string)=>void}){
  return <label className="field-label">{label}<select value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>;
}
function PressurePlot({rows}:{rows:Point[]}){
  const width=680,height=520,left=64,right=24,top=26,bottom=35;
  const values=rows.flatMap(r=>[r.annular_gauge_pa,r.static_gauge_pa,r.lower_assessed_pa,r.upper_assessed_pa,r.tested_min_gauge_pa??r.annular_gauge_pa,r.tested_max_gauge_pa??r.annular_gauge_pa]);
  const low=Math.min(0,...values)/1e6,high=Math.max(...values)/1e6*1.05+.01,td=rows.at(-1)!.md_m;
  const x=(v:number)=>left+(v/1e6-low)/(high-low)*(width-left-right),y=(v:number)=>top+v/Math.max(td,1)*(height-top-bottom);
  const path=(field:keyof Point)=>rows.map((r,i)=>(i?'L':'M')+x(Number(r[field])).toFixed(2)+','+y(r.md_m).toFixed(2)).join(' ');
  const band=rows.map(r=>x(r.tested_min_gauge_pa??r.annular_gauge_pa)+','+y(r.md_m)).concat([...rows].reverse().map(r=>x(r.tested_max_gauge_pa??r.annular_gauge_pa)+','+y(r.md_m))).join(' ');
  return <svg viewBox={'0 0 '+width+' '+height} role="img" aria-label="Annular and static gauge pressure, supplied pressure allowances and tested parameter corners versus measured depth">
    {[0,1,2,3,4].map(i=><g key={i}><line x1={left} x2={width-right} y1={y(td*i/4)} y2={y(td*i/4)} stroke="#e3e9e5"/><text x={left-9} y={y(td*i/4)+4} textAnchor="end">{fmt(td*i/4,0)}</text><text x={left+(width-left-right)*i/4} y={height-12} textAnchor="middle">{fmt(low+(high-low)*i/4,1)}</text></g>)}
    <polygon points={band} fill="#d5e6dc"/><path d={path('lower_assessed_pa')} fill="none" stroke="#b88140" strokeWidth="2" strokeDasharray="5 4"/><path d={path('upper_assessed_pa')} fill="none" stroke="#a26359" strokeWidth="2" strokeDasharray="5 4"/>
    <path d={path('static_gauge_pa')} fill="none" stroke="#7186a3" strokeWidth="2"/><path d={path('annular_gauge_pa')} fill="none" stroke="#216f5d" strokeWidth="2.5"/>
    <text x={left} y={15}>MD (m), increasing downward</text><text x={width-right} y={15} textAnchor="end">Pressure (MPa gauge)</text>
  </svg>;
}
export function Hydraulics({project,online,onError,onNotice,wellboreId,trajectoryRole}:Props){
  const api=engineeringApi({wellboreId,trajectoryRole});
  const scoped=scopeQuery({wellboreId,trajectoryRole});
  const base='/projects/'+project.id;
  const resultView=useRef<HTMLElement|null>(null);
  const [revisions,setRevisions]=useState<Revision[]>([]),[form,setForm]=useState<Input>(()=>initial(project)),[history,setHistory]=useState<Study[]>([]),[result,setResult]=useState<Study|null>(null),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false);
  useEffect(()=>{let active=true;Promise.all([api<Revision[]>(base+'/engineering-revisions?module=M1'+scoped),api<Study[]>(base+'/calculations?model=hydraulics'+scoped)]).then(([r,h])=>{if(active){setRevisions(r);setForm(initial(project,r[0]));setHistory(h);}}).catch(e=>{if(active)onError(e.message);});return()=>{active=false;};},[base,scoped]);
  useEffect(()=>{if(!result)return;const frame=requestAnimationFrame(()=>resultView.current?.scrollIntoView({block:'start'}));return()=>cancelAnimationFrame(frame);},[result?.id]);
  const update=(change:Partial<Input>)=>{setForm(f=>({...f,...change}));setDirty(true);};
  const mud=(change:Partial<Input['mud']>)=>{setForm(f=>({...f,mud:{...f.mud,...change}}));setDirty(true);};
  const window=(change:Partial<Input['pressure_window']>)=>{setForm(f=>({...f,pressure_window:{...f.pressure_window,...change}}));setDirty(true);};
  const sensitivity=(change:Partial<Input['sensitivity']>)=>{setForm(f=>({...f,sensitivity:{...f.sensitivity,...change}}));setDirty(true);};
  const num=(key:keyof Input,label:string,factor=1,min?:number,max?:number,optional=false)=><NumberField label={label} value={form[key] as number|null} onChange={v=>update({[key]:v})} factor={factor} min={min} max={max} optional={optional}/>;
  const note=(key:keyof Input,label:string,optional=false)=><TextField label={label} value={form[key] as string|null} onChange={v=>update({[key]:v||null})} optional={optional}/>;
  const example=async()=>{setBusy(true);try{setForm(await api<Input>(base+'/examples/hydraulics/'+form.geometry_revision_id));setDirty(true);onNotice('Synthetic fluid, string, nozzle, pressure-window and rating assumptions loaded.');}catch(e){onError((e as Error).message);}finally{setBusy(false);}};
  const changeString=(i:number,change:Partial<StringSection>)=>update({string_sections:form.string_sections.map((s,j)=>j===i?{...s,...change}:s)});
  const changeKnot=(i:number,change:Partial<Knot>)=>window({evidence_state:'unreviewed',knots:form.pressure_window.knots.map((k,j)=>j===i?{...k,...change}:k)});
  return <><CalculationFreshness projectId={project.id} calculationId={result?.id}/><div className="scope-note"><div><strong>M6 · Steady single-phase circulation</strong><p>Calculate pipe and concentric-annulus friction with Newtonian, Bingham or Herschel–Bulkley rheology. Hydrostatic head uses TVD; friction uses MD. Continuous margin extrema and tested sensitivity scenarios remain separate from operating approval.</p></div></div>
  <section className="panel hydraulic-editor"><div className="panel-heading"><div><h2>Scenario, mud record & circulation envelope</h2><p>Fully developed laminar flow, stationary concentric walls, constant fluid properties.</p></div>{project.origin==='synthetic'&&<button className="button secondary" onClick={example} disabled={busy||!online||!form.geometry_revision_id}>Load synthetic hydraulics example</button>}</div>
  <form onSubmit={async e=>{e.preventDefault();setBusy(true);onError('');try{const saved=await api<Study>(base+'/calculations/hydraulics',{method:'POST',body:JSON.stringify(form)});setResult(saved);setDirty(false);setHistory(await api<Study[]>(base+'/calculations?model=hydraulics'+scoped));onNotice('Pressure profile, limiting locations and supplied evidence saved.');}catch(e){onError((e as Error).message);}finally{setBusy(false);}}}>
    <div className="lab-fields">
      <label className="field-label">Study name<input required minLength={3} maxLength={100} value={form.study_name} onChange={e=>update({study_name:e.target.value})}/></label>
      <label className="field-label">Geometry context<select required value={form.geometry_revision_id} onChange={e=>{setForm(initial(project,revisions.find(r=>r.id===e.target.value)));setDirty(true);onNotice('New geometry selected. The draft context and evidence states were reset.');}}><option value="">Save M1 geometry first</option>{revisions.map(r=><option key={r.id} value={r.id}>{r.id.slice(0,8)+' · '+r.change_note}</option>)}</select></label>
      <label className="field-label">Declared hydraulic MD datum<input required value={form.depth_datum} onChange={e=>update({depth_datum:e.target.value})}/></label>
      <label className="field-label">Scenario timestamp with UTC offset<input required value={form.scenario_at} onChange={e=>update({scenario_at:e.target.value})}/></label>
      <SelectField label="Well geometry state" value={form.geometry_state} options={[['installed_only','Installed casings only'],['include_planned_scenario','Include planned casing IDs in scenario']]} onChange={v=>update({geometry_state:v})}/>
      <SelectField label="Circulation state" value={form.circulation_state} options={[['unknown','Unknown — withhold'],['steady_single_phase','Steady closed single-phase circulation'],['transient','Transient'],['multiphase','Multiphase'],['losses','Losses / non-conserved circulation']]} onChange={v=>update({circulation_state:v})}/>
      <SelectField label="Flow regime evidence" value={form.flow_regime} options={[['unknown','Unknown — withhold flowing scenario'],['supplied_laminar','Laminar applicability supplied'],['transitional_or_turbulent','Transitional / turbulent — unsupported']]} onChange={v=>update({flow_regime:v})}/>
      {note('applicability_note','Flow/temperature/geometry applicability evidence')}
      <SelectField label="Rheology model" value={form.mud.rheology} options={[['newtonian','Newtonian'],['bingham','Bingham'],['herschel_bulkley','Herschel–Bulkley']]} onChange={v=>mud({rheology:v,...(v==='newtonian'?{flow_index:1,yield_stress_pa:0}:v==='bingham'?{flow_index:1}:{})})}/>
      <NumberField label="Mud density (kg/m³)" value={form.mud.density_kg_m3} min={500} max={3000} onChange={v=>mud({density_kg_m3:v!})}/>
      <NumberField label={'Consistency K (Pa·s^n), n='+fmt(form.mud.flow_index)} value={form.mud.consistency_pa_sn} min={.0001} max={100} onChange={v=>mud({consistency_pa_sn:v!})}/>
      <NumberField label="Flow index n" value={form.mud.flow_index} min={.2} max={1.5} onChange={v=>mud({flow_index:v!})}/>
      <NumberField label="Yield stress (Pa)" value={form.mud.yield_stress_pa} min={0} max={200} onChange={v=>mud({yield_stress_pa:v!})}/>
      <NumberField label="Mud-test temperature (°C)" value={form.mud.test_temperature_c} min={-20} max={250} onChange={v=>mud({test_temperature_c:v!})}/>
      <label className="field-label">Mud measured-at timestamp<input required value={form.mud.measured_at} onChange={e=>mud({measured_at:e.target.value})}/></label>
      {num('maximum_mud_age_hours','Maximum supplied mud age (hours)',1,0,720)}
      <SelectField label="Mud evidence state" value={form.mud.evidence_state} options={[['unknown','Unknown — withhold'],['supplied_measured','Supplied measured record'],...(project.origin==='synthetic'?[['synthetic','Synthetic example'] as [string,string]]:[])]} onChange={v=>mud({evidence_state:v})}/>
      <TextField label="Mud source evidence" value={form.mud.source_note} onChange={v=>mud({source_note:v})}/>
      <TextField label="Density/rheology pressure-temperature basis" value={form.mud.density_rheology_basis_note} onChange={v=>mud({density_rheology_basis_note:v})}/>
      {num('flow_m3_s','Circulation flow (L/min)',1/60000,0,12000)}{num('surface_backpressure_pa','Surface return backpressure (MPa gauge)',1e6,0,100)}
      {num('surface_loss_pa','Supplied upstream surface loss (MPa)',1e6,0,100)}{note('surface_loss_note','Surface-loss source and flow basis')}
      {num('nozzle_total_area_m2','Total nozzle area (mm²)',1e-6,1,20000)}{num('nozzle_discharge_coefficient','Nozzle discharge coefficient',1,.1,1)}{note('nozzle_source_note','Nozzle source evidence')}
    </div>
    <details className="hydraulic-scope-fields"><summary>Unsupported-effect declarations & surface rating</summary><div className="lab-fields">
      {num('rotation_rad_s','String rotation (rad/s)',1,0,1000)}{num('eccentricity_fraction','Eccentricity fraction',1,0,1)}{num('cuttings_volume_fraction','Cuttings volume fraction',1,0,.5)}{num('wall_roughness_m','Wall roughness (mm)',.001,0,10)}
      {num('surface_rating_pa','Supplied surface-supply pressure rating (MPa)',1e6,0,1000,true)}{note('surface_rating_source','Surface rating source',true)}
    </div><p className="well-note">Nonzero rotation, eccentricity or cuttings loading withholds this model. Roughness must stay within its smooth-wall numerical envelope. An absent rating makes the assessment incomplete.</p></details>
    <div className="editor-section-heading"><div><h3>String geometry</h3><p>Ordered contiguous sections from surface to circulation depth; hole/casing IDs come from M1.</p></div><button className="button secondary" type="button" disabled={form.string_sections.length>=30} onClick={()=>{const last=form.string_sections.at(-1)!;const mid=(last.top_md_m+last.bottom_md_m)/2;update({string_sections:[...form.string_sections.slice(0,-1),{...last,bottom_md_m:mid},{...last,name:'Section '+(form.string_sections.length+1),top_md_m:mid}]});}}>Split last section</button></div>
    {form.string_sections.map((s,i)=><div className="record-editor" key={i}><div className="lab-fields">
      <label className="field-label">String name {i+1}<input required value={s.name} onChange={e=>changeString(i,{name:e.target.value})}/></label>
      <NumberField label={'String top MD '+(i+1)+' (m)'} value={s.top_md_m} min={0} onChange={v=>changeString(i,{top_md_m:v!})}/>
      <NumberField label={'String bottom MD '+(i+1)+' (m)'} value={s.bottom_md_m} min={0} onChange={v=>changeString(i,{bottom_md_m:v!})}/>
      <NumberField label={'String OD '+(i+1)+' (mm)'} value={s.outside_diameter_m} factor={.001} min={10} max={1000} onChange={v=>changeString(i,{outside_diameter_m:v!})}/>
      <NumberField label={'String ID '+(i+1)+' (mm)'} value={s.inside_diameter_m} factor={.001} min={5} max={1000} onChange={v=>changeString(i,{inside_diameter_m:v!})}/>
      <TextField label={'String source '+(i+1)} value={s.source_note} onChange={v=>changeString(i,{source_note:v})}/>
    </div>{form.string_sections.length>1&&<button className="text-button" type="button" onClick={()=>update({string_sections:form.string_sections.filter((_,j)=>j!==i)})}>Remove section {i+1}</button>}</div>)}
    <div className="editor-section-heading"><div><h3>Supplied pressure-window knots</h3><p>Surface-atmospheric gauge pressure; piecewise linear in MD. Cover the entire circulation path.</p></div><button type="button" className="button secondary" disabled={form.pressure_window.knots.length>=100} onClick={()=>{const knots=form.pressure_window.knots,a=knots.at(-2)!,b=knots.at(-1)!;const knot=Object.fromEntries(Object.keys(a).map(k=>[k,(a[k as keyof Knot]+b[k as keyof Knot])/2])) as Knot;window({knots:[...knots.slice(0,-1),knot,b],evidence_state:'unreviewed'});}}>Insert midpoint before last knot</button></div>
    <div className="lab-fields"><TextField label="Pressure-window source" value={form.pressure_window.source_note} onChange={v=>window({source_note:v})}/><TextField label="Pressure-window review note" value={form.pressure_window.review_note} onChange={v=>window({review_note:v})}/>
    <SelectField label="Pressure-window evidence state" value={form.pressure_window.evidence_state} options={[['unreviewed','Unreviewed — withhold'],['supplied_reviewed','Supplied reviewed evidence'],...(project.origin==='synthetic'?[['synthetic','Synthetic example'] as [string,string]]:[])]} onChange={v=>window({evidence_state:v})}/></div>
    <details className="pressure-knot-details"><summary>Edit {form.pressure_window.knots.length} pressure-window knots</summary><div className="table-scroll pressure-knot-editor"><table><thead><tr><th>MD (m)</th><th>Pore (MPa gauge)</th><th>Fracture (MPa gauge)</th><th>Pore upper allowance (MPa)</th><th>Fracture lower allowance (MPa)</th><th></th></tr></thead><tbody>{form.pressure_window.knots.map((k,i)=><tr key={i}>{(['md_m','pore_gauge_pa','fracture_gauge_pa','pore_upper_allowance_pa','fracture_lower_allowance_pa'] as (keyof Knot)[]).map(field=><td key={field}><input aria-label={({md_m:'MD (m)',pore_gauge_pa:'Pore pressure (MPa gauge)',fracture_gauge_pa:'Fracture pressure (MPa gauge)',pore_upper_allowance_pa:'Pore upper allowance (MPa)',fracture_lower_allowance_pa:'Fracture lower allowance (MPa)'}[field])+' knot '+(i+1)} required type="number" step="any" min={0} value={Number.isFinite(k[field])?k[field]/(field==='md_m'?1:1e6):''} onChange={e=>changeKnot(i,{[field]:e.target.value===''?NaN:Number(e.target.value)*(field==='md_m'?1:1e6)})}/></td>)}<td>{i>0&&i<form.pressure_window.knots.length-1&&<button type="button" className="text-button" onClick={()=>window({knots:form.pressure_window.knots.filter((_,j)=>j!==i),evidence_state:'unreviewed'})}>Remove knot {i+1}</button>}</td></tr>)}</tbody></table></div></details>
    <div className="editor-section-heading"><div><h3>Tested parameter-corner sensitivity</h3><p>Up to 16 corners; fixed n, yield stress, geometry, nozzle coefficients and supplied surface loss.</p></div></div>
    <div className="lab-fields"><NumberField label="Density perturbation (kg/m³)" value={form.sensitivity.density_delta_kg_m3} min={0} max={500} onChange={v=>sensitivity({density_delta_kg_m3:v!})}/><NumberField label="Flow perturbation (L/min)" value={form.sensitivity.flow_delta_m3_s} factor={1/60000} min={0} max={6000} onChange={v=>sensitivity({flow_delta_m3_s:v!})}/><NumberField label="K relative perturbation (%)" value={form.sensitivity.consistency_relative_delta} factor={.01} min={0} max={50} onChange={v=>sensitivity({consistency_relative_delta:v!})}/><NumberField label="Backpressure perturbation (MPa)" value={form.sensitivity.backpressure_delta_pa} factor={1e6} min={0} max={10} onChange={v=>sensitivity({backpressure_delta_pa:v!})}/></div>
    <button className="button primary" disabled={busy||!online||!form.geometry_revision_id}>{busy?'Calculating profile…':'Calculate and save hydraulics'}</button>
  </form></section>
  {result&&<section ref={resultView} className="panel hydraulic-result"><div className="panel-heading"><div><h2>Preserved pressure profile</h2><p>{result.inputs_si.study_name} · mud age {fmt(result.result.mud_age_hours,2)} hours at the scenario timestamp</p></div><span className="badge amber">No operating approval</span></div>{dirty&&<p className="alert">Inputs have changed. This result retains its original saved inputs and geometry.</p>}
    {result.result.status!=='withheld'&&result.result.reasons.length>0&&<div className="alert"><ul>{result.result.reasons.map(r=><li key={r}>{r}</li>)}</ul></div>}
    {result.result.status==='withheld'?<div className="alert error"><strong>Profile withheld</strong><ul>{result.result.reasons.map(r=><li key={r}>{r}</li>)}</ul></div>:result.result.nominal&&result.result.sensitivity&&<>
      <div className="hydraulic-outcomes"><div><span>Required surface supply</span><strong>{fmt(result.result.nominal.required_supply_gauge_pa/1e6)} MPa</strong><small>Includes supplied upstream loss</small></div><div><span>Minimum lower margin</span><strong>{fmt(result.result.sensitivity.minimum_above_pore.margin_pa/1e6)} MPa</strong><small>MD {fmt(result.result.sensitivity.minimum_above_pore.md_m,1)} m · tested scenarios</small></div><div><span>Minimum upper margin</span><strong>{fmt(result.result.sensitivity.minimum_below_fracture.margin_pa/1e6)} MPa</strong><small>MD {fmt(result.result.sensitivity.minimum_below_fracture.md_m,1)} m · tested scenarios</small></div><div><span>Assessment</span><strong>{result.result.within_all_tested_bounds?'Inside tested bounds':'Outside / incomplete'}</strong><small>{result.result.sensitivity.tested_admissible_corners} admissible corners · {result.result.sensitivity.tested_withheld_corners.length} withheld</small></div></div>
      <div className="hydraulic-visuals"><div><PressurePlot rows={result.result.profile}/><div className="hydraulic-legend"><span>Green: annular pressure</span><span>Blue: static with backpressure</span><span>Brown/red: supplied allowances</span><span>Fill: tested corners</span></div></div><div className="hydraulic-details"><h3>Circulation balance</h3><dl><dt>Annular friction</dt><dd>{fmt(result.result.nominal.annular_loss_pa/1e6)} MPa</dd><dt>Pipe friction</dt><dd>{fmt(result.result.nominal.pipe_loss_pa/1e6)} MPa</dd><dt>Bit/nozzle loss</dt><dd>{fmt(result.result.nominal.bit_loss_pa/1e6)} MPa</dd><dt>Standpipe gauge, after upstream loss</dt><dd>{fmt(result.result.nominal.standpipe_gauge_pa/1e6)} MPa</dd><dt>Maximum tested supply gauge</dt><dd>{fmt(result.result.surface_equipment?.maximum_tested_supply_pa!==undefined?result.result.surface_equipment.maximum_tested_supply_pa/1e6:null)} MPa</dd><dt>Supplied equipment margin</dt><dd>{fmt(result.result.surface_equipment?.margin_pa!=null?result.result.surface_equipment.margin_pa/1e6:null)} MPa</dd><dt>Nominal bottom balance residual</dt><dd>{fmt(result.result.nominal.bottom_path_balance_residual_pa,7)} Pa</dd><dt>Specified inlet / outlet mass flow</dt><dd>{fmt(result.result.nominal.mass_in_kg_s)} / {fmt(result.result.nominal.mass_out_kg_s)} kg/s</dd><dt>Quadrature flow-change indicator</dt><dd>{fmt(result.result.nominal.numerical_loss_change_indicator_pa,5)} Pa · not an error bound</dd></dl><p className="well-note">Equivalent density includes backpressure and is null at zero TVD. Pressure-margin minima use analytic arc extrema between the displayed samples.</p></div></div>
      <h3>Segment losses & applicability screens</h3><div className="table-scroll"><table><thead><tr><th>MD interval (m)</th><th>Effective bore</th><th>Annular / pipe velocity (m/s)</th><th>Annular / pipe loss (MPa)</th><th>Apparent Re screen</th></tr></thead><tbody>{result.result.nominal.segments.map((s,i)=><tr key={i}><td>{fmt(s.top_md_m,1)+'–'+fmt(s.bottom_md_m,1)}</td><td>{s.bore_source}<small>{fmt(s.bore_diameter_m*1000,1)} mm ID</small></td><td>{fmt(s.annular_velocity_m_s)+' / '+fmt(s.pipe_velocity_m_s)}</td><td>{fmt(s.annular_loss_pa/1e6)+' / '+fmt(s.pipe_loss_pa/1e6)}</td><td>{fmt(s.annular_re_screen,1)+' / '+fmt(s.pipe_re_screen,1)}</td></tr>)}</tbody></table></div>
      <details><summary>Profile points, complete sensitivity & limiting locations</summary><div className="table-scroll"><table><thead><tr><th>MD / TVD (m)</th><th>Annular / pipe (MPa gauge)</th><th>Lower / upper margin (MPa)</th><th>Equivalent density including backpressure (kg/m³)</th></tr></thead><tbody>{result.result.profile.slice(0,100).map((p,i)=><tr key={i}><td>{fmt(p.md_m,2)+' / '+fmt(p.tvd_m,2)}</td><td>{fmt(p.annular_gauge_pa/1e6)+' / '+fmt(p.pipe_gauge_pa/1e6)}</td><td>{fmt(p.above_pore_allowance_pa/1e6)+' / '+fmt(p.below_fracture_allowance_pa/1e6)}</td><td>{fmt(p.equivalent_density_including_backpressure_kg_m3,1)}</td></tr>)}</tbody></table></div><p className="well-note">First 100 profile points shown; full computed profile and all sensitivity cases are preserved in the report.</p><pre>{JSON.stringify(result.result.sensitivity,null,2)}</pre></details>
    </>}
    <ul className="model-warnings">{result.result.warnings.map(w=><li key={w}>{w}</li>)}</ul><details><summary>Saved inputs & geometry/source hashes</summary><pre>{JSON.stringify({id:result.id,created_at:result.created_at,inputs:result.inputs_si,geometry_sha256:result.result.geometry_sha256,survey_source_sha256:result.result.survey_source_sha256},null,2)}</pre></details>
  </section>}
  <section className="panel"><div className="panel-heading"><div><h2>Saved hydraulic studies</h2><p>Reopen the original scenario; later input edits do not change saved evidence.</p></div></div><div className="hydraulic-history">{history.map(h=><button className="button secondary" key={h.id} onClick={()=>{setResult(h);setDirty(true);}}>{h.inputs_si.study_name+' · '+h.result.status+' · '+new Date(h.created_at).toLocaleString()}</button>)}{!history.length&&<div className="empty-inline">No saved hydraulic studies.</div>}</div></section>
  </>;
}
