import {useEffect,useState} from 'react';
import {Plus,Trash2} from 'lucide-react';
import {api} from './api';
import type {Revision} from './GeometryWorkspace';

type Feature={curve:string;unit:string;transform:'identity'|'log10';minimum:number;maximum:number;range_basis:string};
type Dataset={id:string;kind:string;filename:string;row_count:number;metadata:Record<string,unknown>};
type Result={id:string;created_at:string;inputs_si:Record<string,unknown>;result:{
  status:string;reason:string;training_count:number;excluded_count:number;seed:number;selected_seed?:number;inertia?:number;initialization_agreement_min_ari?:number;
  rows:{source_index:number;depth_m:number;cluster:number|null;distance:number|null;status:string;reason:string}[];
  centers:{cluster:number;standardized:number[];response_centers:Record<string,number>;training_count:number}[];
  scaling:{curve:string;unit:string;transform:string;training_mean:number;training_population_std:number}[];
  intervals:{cluster:number;first_sample_md_m:number;last_sample_md_m:number;sample_count:number}[];
  warnings:string[];geometry_revision_id:string;source_sha256:string;
}};
const colors=['#216f5d','#b57524','#647db1','#a75a80','#648131','#8c6850','#3c90a5','#8972a3'];
const fmt=(n:number|null|undefined,d=3)=>n==null?'—':n.toLocaleString('en-US',{maximumFractionDigits:d});
export function LogClustering({project,datasets,online,onError,onNotice}:{project:{id:string;datum:string;origin:string};datasets:Dataset[];online:boolean;onError:(s:string)=>void;onNotice:(s:string)=>void}){
  const base='/projects/'+project.id;
  const [source,setSource]=useState(datasets.find(d=>d.kind==='las')?.id??''),[curves,setCurves]=useState<{mnemonic:string;unit:string}[]>([]);
  const [revisions,setRevisions]=useState<Revision[]>([]),[revisionId,setRevisionId]=useState(''),[features,setFeatures]=useState<Feature[]>([]);
  const [history,setHistory]=useState<Result[]>([]),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false);
  useEffect(()=>{let alive=true;Promise.all([api<Revision[]>(base+'/engineering-revisions?module=M1'),api<Result[]>(base+'/calculations?model=clustering')]).then(([r,h])=>{if(alive){setRevisions(r);setRevisionId(r[0]?.id??'');setHistory(h);}}).catch(e=>{if(alive)onError(e.message);});return()=>{alive=false;};},[base]);
  useEffect(()=>{let alive=true;setCurves([]);setFeatures([]);setDirty(true);if(source)api<Dataset>(base+'/datasets/'+source).then(d=>{if(alive)setCurves((d.metadata.curves as {mnemonic:string;unit:string}[]).slice(1));}).catch(e=>{if(alive)onError(e.message);});return()=>{alive=false;};},[base,source]);
  const synthetic=()=>{setFeatures(curves.filter(c=>['GR','RHOB'].includes(c.mnemonic)).map(c=>({curve:c.mnemonic,unit:c.unit,transform:'identity',minimum:c.mnemonic==='GR'?0:1,maximum:c.mnemonic==='GR'?150:3.5,range_basis:'Synthetic software demonstration envelope; not a qualified tool range'})));setDirty(true);};
  return <><div className="scope-note"><div><strong>M3 · Exploratory log response clustering</strong><p>Group native-depth observations using explicit feature envelopes and training scaling. Cluster IDs and distances require geological review; they do not confirm lithology.</p></div></div>
  <div className="panel log-clustering"><form onChange={()=>setDirty(true)} onSubmit={async e=>{e.preventDefault();setBusy(true);onError('');try{const f=new FormData(e.currentTarget);const value={dataset_id:source,geometry_revision_id:revisionId,study_name:f.get('study'),depth_datum:f.get('datum'),features,clusters:Number(f.get('clusters')),seed:Number(f.get('seed')),fit_top_md_m:Number(f.get('top')),fit_bottom_md_m:Number(f.get('bottom')),maximum_native_gap_m:Number(f.get('gap')),depth_alignment_note:f.get('alignment'),correction_status:f.get('correction_status'),correction_note:f.get('correction_note'),acquisition_quality_note:f.get('quality')};const r=await api<Result>(base+'/calculations/clustering',{method:'POST',body:JSON.stringify(value)});setResult(r);setDirty(false);setHistory(await api<Result[]>(base+'/calculations?model=clustering'));onNotice('Clustering inputs, scaling, native-depth assignments and provenance saved.');}catch(e){onError((e as Error).message);}finally{setBusy(false);}}}>
    <div className="panel-heading"><div><h2>Analysis inputs & applicability</h2><p>Original curve units are retained. Each run uses three reproducible k-means++ initializations.</p></div></div>
    <div className="lab-fields"><label className="field-label">Study name<input name="study" required minLength={3} maxLength={100}/></label><label className="field-label">LAS source<select value={source} onChange={e=>setSource(e.target.value)} required><option value="">Select a source</option>{datasets.filter(d=>d.kind==='las').map(d=><option key={d.id} value={d.id}>{d.filename+' · '+d.row_count+' native samples'}</option>)}</select></label><label className="field-label">Geometry context<select value={revisionId} onChange={e=>setRevisionId(e.target.value)} required><option value="">Save M1 geometry first</option>{revisions.map(r=><option key={r.id} value={r.id}>{r.id.slice(0,8)+' · '+r.change_note}</option>)}</select></label><label className="field-label">Declared log MD datum<input name="datum" required defaultValue={project.datum}/></label><label className="field-label">Clusters<input name="clusters" type="number" required min="2" max="8" defaultValue="2"/></label><label className="field-label">Random seed<input name="seed" type="number" required min="0" max="2147483647" defaultValue="42"/></label><label className="field-label">Training top MD (m)<input name="top" type="number" required min="0" max="30000" step="any" defaultValue={project.origin==='synthetic'?2400:''}/></label><label className="field-label">Training bottom MD (m)<input name="bottom" type="number" required min="0" max="30000" step="any" defaultValue={project.origin==='synthetic'?2404:''}/></label><label className="field-label">Maximum gap joining sample intervals (m)<input name="gap" type="number" required min=".0001" max="1000" step="any" defaultValue="2"/></label><label className="field-label">Tool / environmental correction state<select name="correction_status" defaultValue="unknown"><option value="unknown">Unknown</option><option value="raw">Raw / uncorrected</option><option value="corrected">Supplied corrected curves</option></select></label><label className="field-label">Depth alignment / tool response evidence<textarea name="alignment" required minLength={3} maxLength={400} placeholder="Explain MD datum, tool offsets and response resolution; resolve shifts before importing."/></label><label className="field-label">Correction evidence<textarea name="correction_note" required minLength={3} maxLength={400}/></label><label className="field-label">Acquisition quality / caliper evidence<textarea name="quality" required minLength={3} maxLength={400}/></label></div>
    <div className="editor-section-heading"><h3>Selected features</h3><div className="button-group">{project.origin==='synthetic'&&<button className="button secondary" type="button" disabled={!curves.length} onClick={synthetic}>Load synthetic feature envelope</button>}<button className="button secondary" type="button" disabled={!curves.length||features.length>=8} onClick={()=>{const c=curves.find(c=>!features.some(f=>f.curve===c.mnemonic));if(c){setFeatures(v=>[...v,{curve:c.mnemonic,unit:c.unit,transform:'identity',minimum:0,maximum:1000,range_basis:''}]);setDirty(true);}}}><Plus size={15}/>Add feature</button></div></div>
    {features.map((f,i)=>{const set=(patch:Partial<Feature>)=>{setFeatures(v=>v.map((x,j)=>i===j?{...x,...patch}:x));setDirty(true);};return <div className="record-editor" key={i}><div className="lab-fields"><label className="field-label">Curve<select value={f.curve} onChange={e=>{const c=curves.find(c=>c.mnemonic===e.target.value)!;set({curve:c.mnemonic,unit:c.unit});}}>{curves.filter(c=>c.mnemonic===f.curve||!features.some(f=>f.curve===c.mnemonic)).map(c=><option key={c.mnemonic} value={c.mnemonic}>{c.mnemonic+' ['+(c.unit||'unit unspecified')+']'}</option>)}</select></label><label className="field-label">Transform<select value={f.transform} onChange={e=>set({transform:e.target.value as Feature['transform']})}><option value="identity">Identity</option><option value="log10">Log10 (positive values only)</option></select></label><label className="field-label">Minimum ({f.unit})<input type="number" required step="any" value={f.minimum} onChange={e=>set({minimum:Number(e.target.value)})}/></label><label className="field-label">Maximum ({f.unit})<input type="number" required step="any" value={f.maximum} onChange={e=>set({maximum:Number(e.target.value)})}/></label><label className="field-label">Feature envelope basis<input required minLength={3} maxLength={300} value={f.range_basis} onChange={e=>set({range_basis:e.target.value})}/></label></div><button type="button" className="text-button" onClick={()=>{setFeatures(v=>v.filter((_,j)=>i!==j));setDirty(true);}}><Trash2 size={14}/>Remove feature</button></div>;})}
    <div className="lab-action"><button className="button primary" disabled={busy||!online||!revisionId||!features.length}>{busy?'Clustering…':'Run & save exploratory analysis'}</button><p className="small-note">Up to 2,500 samples and eight features. Missing values are withheld; scaling is fitted only within the selected training interval.</p></div>
  </form></div>
  {result&&<div className="panel clustering-result"><div className="panel-heading"><div><h2>{String(result.inputs_si.study_name)} <span className="badge amber">{result.result.status.replaceAll('_',' ')}</span></h2><p>{result.result.reason}</p></div></div>{dirty&&<p className="inset-note">This preserved result uses its saved inputs. Current form edits have not been calculated.</p>}
    <div className="lab-fields"><p>Training observations <strong>{result.result.training_count}</strong></p><p>Withheld observations <strong>{result.result.excluded_count}</strong></p><p>Selected initialization <strong>{result.result.selected_seed??'—'}</strong></p><p>Initialization agreement, minimum ARI <strong>{fmt(result.result.initialization_agreement_min_ari)}</strong></p></div>
    <div className="clustering-visuals"><ClusterDepth result={result.result}/><div><h3>Response centers in source units</h3><div className="table-scroll"><table><thead><tr><th>Cluster</th>{result.result.scaling.map(f=><th key={f.curve}>{f.curve+' ['+f.unit+']'}</th>)}<th>Training count</th></tr></thead><tbody>{result.result.centers.map(c=><tr key={c.cluster}><td><span style={{color:colors[c.cluster-1]}}>●</span> {c.cluster}</td>{result.result.scaling.map(f=><td key={f.curve}>{fmt(c.response_centers[f.curve])}</td>)}<td>{c.training_count}</td></tr>)}</tbody></table></div><p className="small-note">For log10 features, displayed response centers are back-transformed centers; they are not arithmetic means of raw observations.</p><h3>Contiguous sample groups</h3><div className="table-scroll"><table><thead><tr><th>Cluster</th><th>First MD (m)</th><th>Last MD (m)</th><th>Samples</th></tr></thead><tbody>{result.result.intervals.slice(0,100).map((r,i)=><tr key={i}><td>{r.cluster}</td><td>{fmt(r.first_sample_md_m)}</td><td>{fmt(r.last_sample_md_m)}</td><td>{r.sample_count}</td></tr>)}</tbody></table></div><p className="small-note">Groups end at withheld rows or gaps exceeding the supplied threshold. Sample bounds are not interpreted bed boundaries; first 100 groups shown.</p></div></div>
    <details className="inset-note"><summary>Feature scaling and preserved inputs</summary><pre>{JSON.stringify({scaling:result.result.scaling,inputs:result.inputs_si,source_sha256:result.result.source_sha256,geometry_revision_id:result.result.geometry_revision_id},null,2)}</pre></details><details className="inset-note"><summary>Native-depth assignments · first 100 samples</summary><div className="table-scroll"><table><thead><tr><th>Source index</th><th>MD (m)</th><th>Cluster</th><th>Distance</th><th>State / reason</th></tr></thead><tbody>{result.result.rows.slice(0,100).map(r=><tr key={r.source_index}><td>{r.source_index}</td><td>{fmt(r.depth_m)}</td><td>{r.cluster??'—'}</td><td>{fmt(r.distance)}</td><td>{r.status+' · '+r.reason}</td></tr>)}</tbody></table></div></details>
    <div className="inset-note">{result.result.warnings.map(w=><p key={w}>{w}</p>)}</div>
  </div>}
  <div className="panel"><div className="panel-heading"><div><h2>Preserved analyses</h2><p>Results reopen with their original inputs and scaling. Create a report to export complete assignments.</p></div></div><div className="table-scroll"><table><thead><tr><th>Study</th><th>Source geometry</th><th>Training samples</th><th>State</th><th/></tr></thead><tbody>{history.map(h=><tr key={h.id}><td>{String(h.inputs_si.study_name)}</td><td>{h.result.geometry_revision_id.slice(0,8)}</td><td>{h.result.training_count}</td><td>{h.result.status.replaceAll('_',' ')}</td><td><button className="text-button" onClick={()=>{setResult(h);setDirty(true);}}>Open saved analysis</button></td></tr>)}</tbody></table></div></div></>;
}
function ClusterDepth({result}:{result:Result['result']}){
  const rows=result.rows,top=Math.min(...rows.map(r=>r.depth_m)),bottom=Math.max(...rows.map(r=>r.depth_m)),range=Math.max(bottom-top,1);
  return <div><h3>Native-depth cluster track</h3><svg viewBox="0 0 360 440" role="img" aria-label="Cluster assignment at native sample depths; missing or ineligible samples shown as crosses"><rect x="65" y="25" width="275" height="360" fill="#f4f6f0"/>{[0,1,2,3,4].map(i=><g key={i}><line x1="65" x2="340" y1={25+i*90} y2={25+i*90} stroke="#d6dfd0"/><text x="58" y={29+i*90} textAnchor="end" fontSize="11">{fmt(top+range*i/4,1)}</text></g>)}{rows.map(r=>{const x=r.cluster===null?80:105+(r.cluster-1)*30,y=25+(r.depth_m-top)/range*360;return <g key={r.source_index}><title>{'MD '+r.depth_m+' m · '+r.reason}</title>{r.cluster===null?<text x={x} y={y+4} textAnchor="middle" fill="#a56b20">×</text>:<circle cx={x} cy={y} r="3" fill={colors[r.cluster-1]}/>}</g>})}<text x="65" y="420" fontSize="11">MD (m) increases down · numbered clusters →</text></svg></div>;
}
