import {useEffect,useRef,useState} from 'react';
import {api} from './api';
import type {Revision} from './GeometryWorkspace';

type Value=string|number|boolean|null|Value[]|{[key:string]:Value};
type Document=Record<string,Value>;
type Schema={$ref?:string;type?:string;title?:string;description?:string;enum?:string[];anyOf?:Schema[];properties?:Record<string,Schema>;items?:Schema;required?:string[];$defs?:Record<string,Schema>;minimum?:number;maximum?:number;minLength?:number;maxLength?:number};
type Model='stability'|'transport'|'surge-swab'|'torque-drag'|'buckling'|'dynamics'|'bit-condition'|'wear-fatigue'|'anomaly'|'gas-phase'|'supervision';
type Study={id:string;model:string;inputs_si:Document;result:Document;created_at:string};
type Props={model:Model;project:{id:string;origin:string;datum:string};online:boolean;onError:(s:string)=>void;onNotice:(s:string)=>void};
const descriptions:Record<Model,[string,string]>={
  dynamics:['M12 · BHA dynamics & measurements','Simulate three coupled coordinates of a straight uniform cantilever segment. Review supplied acceleration samples separately; bandwidth eligibility does not establish modal observability or a virtual downhole diagnosis.'],
  'bit-condition':['M13 · Inspected bit runs','Preserve inspections, run exposure and measured or proxy energy. Compare censored runs within one family and formation using evidence available at the declared cutoff. Cohort survival and conditional costs do not predict an individual bit life or authorize a trip.'],
  'wear-fatigue':['M14 · Casing exposure, wear & fatigue','Track material-specific contact wear separately from Miner fatigue exposure. Compare inspected wall measurements and restrict the residual pressure/yield screen to a uniform wall with declared complete exposure.'],
  anomaly:['M15 · Flow & stock balance replay','Review native mass-flow and contained-mass records in a declared control volume. Causal residual persistence is a balance-anomaly candidate; operation changes and unknown intervals interrupt the alarm. Supplied labels support replay evaluation only.'],
  'gas-phase':['M16 · Characterized phase studies','Verify a characterized nonpolar binary Peng–Robinson equilibrium or review an external mud/gas phase study. Batch replay uses prescribed external boundaries and preserves total gas inventory. This does not predict drilling-mud solubility or exact emergence depth.'],
  supervision:['M17 · Supervisory software research','Simulate a pressure plant and bounded PID requests. The independent simulation validator checks configuration, lease, expiry, idempotency, slew, interlocks and overrides. There is no rig network adapter or equipment-command interface.'],
  stability:['M7 · Elastic & thermal stability','Explore effective wall stresses in an isotropic elastic rock with an impermeable mudcake. Thermal effects use a restrained-wall estimate. Strength screens and externally supplied pressure bounds remain research assumptions.'],
  transport:['M8 · Cuttings transport','Track generated, returned and retained solids using a conserved tank model. Stokes settling applies to dilute spherical particles in near-vertical Newtonian flow. No universal cleaning velocity is inferred.'],
  'surge-swab':['M9 · Offline surge & swab','Model acoustic pressure changes driven by a pipe-motion history in a uniform annulus. Check the complete time history against supplied pressure windows, with grid refinement and compressible-storage balance.'],
  buckling:['M11 · Buckling & load transfer','Assess local effective compression in straight inclined uniform pipe intervals. Select a saved M10 source, declare stiffness and boundaries, and compare model-specific thresholds with uncertainty. Conditional helical drag solves a separate interval equilibrium.'],
  'torque-drag':['M10 · Soft-string torque & drag','Explore pickup, slackoff, rotation or combined motion with buoyant weight, curvature contact and Coulomb friction. Compare supplied surface observations and friction sensitivity; MSE remains available in Engineering lab.']
};
const labels:Record<string,string>={cutoff_at:'Analysis cutoff (ISO time with zone)',closed_end_von_mises_pa:'Closed-end von Mises stress (MPa)',miner_damage:'Miner fatigue index',horizon_failure_fraction:'Conditional horizon failure fraction',boundary:'End boundary model',pipe_configuration:'Pipe and contact configuration',force_basis:'Axial force basis',wall_loads:'Supplied wall-force and absolute-pressure knots',compression_allowance_n:'Local compression uncertainty (kN)',modulus_relative_delta:'Modulus relative uncertainty',clearance_relative_delta:'Clearance relative uncertainty',transfer_model:'Load-transfer assessment',transfer_tolerance_n:'Load-transfer refinement tolerance (kN)',source_note:'Evidence and applicability',md_m:'Measured depth (m)',evidence_state:'Input evidence state',model:'Rock model',thermal_scope:'Thermal model',external_bounds_state:'External pressure-bound evidence',pressure_basis_note:'Stress and pressure reference / boundary evidence',hydraulics_calculation_id:'Saved hydraulic source',displacement:'Pipe displacement / fill model',operation:'String operation',motion:'Pipe-motion history',string_sections:'String sections',generation_stop_s:'Generation stops at (s)',shape:'Particle shape',cells:'Initial grid cells',convergence_tolerance_pa:'Pressure refinement tolerance (MPa)',step_m:'Initial integration step (m)'};
function presentation(key:string):[string,number]{
  if(key==='wear_coefficient_m2_n')return ['Wear coefficient (m²/N)',1];
  if(key==='contact_work_n_m')return ['Integrated normal-force × sliding exposure (N·m)',1];
  if(key==='proportional_per_pa')return ['Proportional gain (1/Pa)',1];
  if(key==='integral_per_pa_s')return ['Integral gain (1/(Pa·s))',1];
  if(key==='derivative_s_per_pa')return ['Derivative gain (s/Pa)',1];
  if(key==='completed_at')return ['Run observation ends at (ISO time with zone)',1];
  if(key==='available_at')return ['Evidence available at (ISO time with zone)',1];
  if(key==='young_modulus_pa')return ['Young modulus (GPa)',1e9];
  if(key==='rop_m_s')return ['Rate of penetration (m/h)',1/3600];
  if(labels[key])return [labels[key],key.endsWith('_pa')?1e6:key.endsWith('_n')?1000:1];
  const units:[string,string,number][]=[['_m3_mol','m³/mol',1],['_n_per_m','N/m',1],['_mol','mol',1],['_hz','Hz',1],['_m2','m²',1],['_kg_s','kg/s',1],['_rad_s2','rad/s²',1],['_m_s2','m/s²',1],['_j','J',1],['_hours','hours',1],['_rad','rad',1],['_m3','m³',1],['_kg','kg',1],['_kg_m3','kg/m³',1],['_m3_s','L/min',1/60000],['_pa','MPa',1e6],['_nm','kN·m',1000],['_n','kN',1000],['_rad_s','rad/s',1],['_m_s','m/s',1],['_per_k','1/K',1],['_deg','°',1],['_k','K',1],['_s','s',1],['_m','m',1]];
  for(const [suffix,unit,factor] of units.sort((a,b)=>b[0].length-a[0].length))if(key.endsWith(suffix))return [key.slice(0,-suffix.length).replaceAll('_',' ').replace(/^./,c=>c.toUpperCase())+' ('+unit+')',factor];
  return [key.replaceAll('_',' ').replace(/^./,c=>c.toUpperCase()),1];
}
const sensorUnit=(s:Value)=>s==='m_s2'?'m/s²':s==='rad_s2'?'rad/s²':String(s);
const human=(s:string)=>s.replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());
const fmt=(v:Value|undefined,d=3)=>typeof v==='number'?(v!==0&&Math.abs(v)<1e-5?v.toExponential(3):v.toLocaleString('en-US',{maximumFractionDigits:d})):v==null?'Not supplied':String(v);
function resolve(schema:Schema,root:Schema):Schema{
  if(schema.$ref)return root.$defs?.[schema.$ref.split('/').at(-1)!]??schema;
  if(schema.anyOf)return schema.anyOf.find(s=>s.type!=='null')??schema;
  return schema;
}
function empty(schema:Schema,root:Schema):Value{
  const s=resolve(schema,root);
  if(s.type==='object')return Object.fromEntries(Object.entries(s.properties??{}).map(([k,v])=>[k,empty(v,root)]));
  if(s.type==='array')return [];
  if(s.enum)return s.enum[0];
  if(s.type==='boolean')return false;
  return s.type==='number'||s.type==='integer'?s.minimum??0:'';
}
function Field({name,schema,root,value,onChange,required=false}:{name:string;schema:Schema;root:Schema;value:Value;onChange:(v:Value)=>void;required?:boolean}){
  const s=resolve(schema,root);const [label,factor]=presentation(name);const optional=schema.anyOf?.some(x=>x.type==='null')??false;
  if(s.type==='object'){
    const obj=(value??{}) as Document;
    return <fieldset className="research-group"><legend>{label}</legend><div className="lab-fields">{Object.entries(s.properties??{}).map(([k,sub])=><Field key={k} name={k} schema={sub} root={root} value={obj[k]??null} required={s.required?.includes(k)} onChange={v=>onChange({...obj,[k]:v})}/>)}</div></fieldset>;
  }
  if(s.type==='array'){
    const rows=(value??[]) as Value[];const item=s.items??{};
    return <fieldset className="research-group"><legend>{label}</legend>{rows.length>24&&<p className="well-note">{rows.length} records retained. First 24 are editable here; use the full SI JSON export/import for larger histories.</p>}{rows.slice(0,24).map((row,i)=><div className="research-array" key={i}><Field name={'Record '+(i+1)} schema={item} root={root} value={row} onChange={v=>onChange(rows.map((r,j)=>j===i?v:r))}/><button type="button" className="text-button" aria-label={'Remove '+label+' record '+(i+1)} onClick={()=>onChange(rows.filter((_,j)=>j!==i))}>Remove record {i+1}</button></div>)}<button type="button" className="button secondary" onClick={()=>onChange([...rows,rows.length?structuredClone(rows.at(-1)!):empty(item,root)])}>Add {label.toLowerCase()} record</button></fieldset>;
  }
  if(s.type==='boolean')return <label className="field-label research-checkbox"><span>{label}</span><input type="checkbox" checked={value===true} onChange={e=>onChange(e.target.checked)}/></label>;
  if(s.enum)return <label className="field-label">{label}<select value={String(value??'')} required={required} onChange={e=>onChange(e.target.value)}>{s.enum.map(option=><option key={option} value={option}>{human(option)}</option>)}</select></label>;
  if(s.type==='number'||s.type==='integer')return <label className="field-label">{label}<input type="number" step={s.type==='integer'?1:'any'} value={value===null?'':Number(value)/factor} required={required&&!optional} min={s.minimum===undefined?undefined:s.minimum/factor} max={s.maximum===undefined?undefined:s.maximum/factor} onChange={e=>onChange(e.target.value===''?null:Number(e.target.value)*factor)}/></label>;
  return <label className="field-label">{label}{name.includes('note')?<textarea rows={2} value={String(value??'')} required={required&&!optional} minLength={s.minLength} maxLength={s.maxLength} onChange={e=>onChange(e.target.value||null)}/>:<input value={String(value??'')} required={required&&!optional} minLength={s.minLength} maxLength={s.maxLength} onChange={e=>onChange(e.target.value||null)}/>}</label>;
}
type Series={key:string;label:string;color:string};
function Plot({rows,xKey,series,factor=1,xLabel,yLabel,step=false,breakKey,range}:{rows:Document[];xKey:string;series:Series[];factor?:number;xLabel:string;yLabel:string;step?:boolean;breakKey?:string;range?:[number,number]}){
  const finite=rows.filter(r=>typeof r[xKey]==='number');
  if(!finite.length)return null;
  const xs=finite.map(r=>Number(r[xKey])),ys=finite.flatMap(r=>series.filter(s=>typeof r[s.key]==='number').map(s=>Number(r[s.key])/factor)).filter(Number.isFinite);
  if(!ys.length)return null;
  const loX=xs.reduce((a,b)=>Math.min(a,b),Infinity),hiX=xs.reduce((a,b)=>Math.max(a,b),-Infinity);let loY=ys.reduce((a,b)=>Math.min(a,b),Infinity),hiY=ys.reduce((a,b)=>Math.max(a,b),-Infinity);
  const pad=Math.max((hiY-loY)*.08,Math.abs(hiY)*.01,hiY===loY?1:1e-9);if(range){loY=range[0];hiY=range[1];}else{loY-=pad;hiY+=pad;}
  const px=(x:number)=>65+(x-loX)/(hiX-loX||1)*700;const py=(y:number)=>275-(y-loY)/(hiY-loY)*230;
  return <div className="research-plot"><svg viewBox="0 0 820 325" role="img" aria-label={yLabel+' versus '+xLabel}>{[0,1,2,3,4].map(i=>{const y=loY+(hiY-loY)*i/4;return <g key={i}><line x1="65" x2="765" y1={py(y)} y2={py(y)} stroke="#e2e8f0"/><text x="57" y={py(y)+4} textAnchor="end" fontSize="11" fill="#64748b">{y.toPrecision(3)}</text></g>;})}<line x1="65" x2="765" y1="275" y2="275" stroke="#94a3b8"/>{series.flatMap(s=>{const paths:string[][]=[];let path:string[]=[];let previous:Document|undefined;for(const row of finite){if(breakKey&&row[breakKey]==="unknown_balance"){if(path.length)paths.push(path);path=[];previous=undefined;}if(typeof row[s.key]!=='number'){if(path.length)paths.push(path);path=[];previous=undefined;continue;}if(step&&previous)path.push(px(Number(row[xKey]))+','+py(Number(previous[s.key])/factor));path.push(px(Number(row[xKey]))+','+py(Number(row[s.key])/factor));previous=row;}if(path.length)paths.push(path);return paths.map((points,i)=><polyline key={s.key+i} fill="none" stroke={s.color} strokeWidth="2" points={points.join(' ')}/>);})}<text x="65" y="295" fontSize="11">{loX.toFixed(1)}</text><text x="765" y="295" textAnchor="end" fontSize="11">{hiX.toFixed(1)}</text><text x="410" y="315" textAnchor="middle" fontSize="12">{xLabel}</text><text x="65" y="20" fontSize="12">{yLabel}</text></svg><div className="research-legend">{series.map(s=><span key={s.key}><i style={{background:s.color}}/>{s.label}</span>)}</div></div>;
}
const palette=['#0f766e','#d97706','#6366f1','#be185d'];
const historyPlots:Record<Model,[string[],number,string][]>={stability:[],buckling:[],'torque-drag':[],
  transport:[[['generated_m3','returned_m3','inventory_m3'],1,'Solids volume (m³)']],
  'surge-swab':[[['bottom_perturbation_pa'],1e6,'Bottom-cell pressure change (MPa)']],
  dynamics:[[['axial_displacement_m','lateral_displacement_m'],1,'Simulated displacement (m)'],[['torsional_angle_rad'],1,'Simulated torsional angle (rad)'],[['energy_j','energy_balance_residual_j'],1,'Simulated energy and balance residual (J)']],
  'bit-condition':[],'wear-fatigue':[],
  anomaly:[[['inlet_kg_s','outlet_kg_s','transfer_into_kg_s'],1,'Native mass flows (kg/s)'],[['contained_mass_kg'],1,'Native contained mass (kg)'],[['residual_kg_s','meter_lower_kg_s','meter_upper_kg_s'],1,'Causal mass-balance residual (kg/s); gaps remain unknown']],
  'gas-phase':[[['dissolved_gas_mol','free_gas_mol'],1,'Closed batch gas inventory (mol)'],[['free_gas_volume_m3'],1,'Prescribed-boundary free-gas volume (m³)']],
  supervision:[[['pressure_pa','target_pressure_pa'],1e6,'Software plant pressure (MPa)'],[['simulated_actuator_fraction','requested_fraction'],1,'Simulated actuator fraction']]
};
function preview(value:Value|undefined):Value{
  if(value===undefined)return null;
  if(Array.isArray(value))return value.length>12?[...value.slice(0,12).map(preview),{retained_records:value.length,display:'First 12; full data retained in the saved report'}]:value.map(preview);
  if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,preview(v)]));
  return value;
}
function EvidenceObject({title,value}:{title:string;value:Value|undefined}){
  if(value===undefined)return null;
  const entries=value&&typeof value==='object'&&!Array.isArray(value)?Object.entries(value):[];
  const scalar=entries.filter(([,v])=>v===null||typeof v!=='object');
  const nested=Object.fromEntries(entries.filter(([,v])=>v!==null&&typeof v==='object'));
  return <section className="panel"><div className="panel-heading"><h2>{title}</h2></div>{scalar.length>0?<dl className="research-evidence">{scalar.map(([key,v])=>{const [label,factor]=presentation(key);return <div key={key}><dt>{label}</dt><dd>{typeof v==='number'?fmt(v/factor,8):v===null?'Not supplied':typeof v==='string'?human(v):fmt(v)}</dd></div>;})}</dl>:null}
    {(Object.keys(nested).length>0||!entries.length)&&<details><summary>Inspect numerical values · SI units</summary><pre className="research-json">{JSON.stringify(preview(entries.length?nested:value),null,2)}</pre></details>}</section>;
}
function EvidenceTable({title,rows,columns}:{title:string;rows:Document[];columns:string[]}){
  if(!rows.length)return null;
  return <section className="panel"><div className="panel-heading"><div><h2>{title}</h2><p>{rows.length} retained records; complete evidence preserved in reports.</p></div></div><div className="table-scroll"><table><thead><tr>{columns.map(k=><th key={k}>{presentation(k)[0]}</th>)}</tr></thead><tbody>{rows.slice(0,80).map((r,i)=><tr key={i}>{columns.map(k=><td key={k}>{Array.isArray(r[k])?(r[k] as Value[]).map(v=>fmt(v)).join(', '):typeof r[k]==='number'?fmt(Number(r[k])/presentation(k)[1],6):k==='units'?sensorUnit(r[k]):['axis','status','termination'].includes(k)?human(fmt(r[k])):fmt(r[k])}</td>)}</tr>)}</tbody></table></div></section>;
}

function Result({model,result}:{model:Model;result:Document}){
  const profile=(result.profile??[]) as Document[],history=(result.history??[]) as Document[];
  const summaries:Record<Model,string[]>={
    dynamics:['maximum_energy_balance_residual_j','contact_active_samples'],
    'bit-condition':['cohort_size','confirmed_failures'],
    'wear-fatigue':['contact_work_n_m','wear_volume_m3','predicted_minimum_wall_m','conservative_minimum_wall_m','inspection_residual_m'],
    anomaly:['valid_monitoring_duration_s','unknown_intervals','probabilities_calibrated','actuation_available'],
    'gas-phase':['maximum_inventory_residual_mol','initial_refinement_mol','final_refinement_mol','native_mud_solubility_prediction'],
    supervision:['final_pressure_pa','tracking_rms_pa','maximum_overshoot_pa','refinement_change_pa','pressure_envelope_exceeded','accepted_simulation_requests','rejected_simulation_requests','equipment_control','network_adapter_available'],buckling:['sinusoidal_threshold_n','helical_threshold_n','maximum_compression_n','minimum_conservative_margin_n','radial_clearance_m','characteristic_wavelength_m'],stability:['thermal_stress_estimate_pa','failure_screen_exceeded','angular_resolution_deg'],transport:['settling_velocity_m_s','particle_reynolds','generated_m3','returned_m3','inventory_m3','peak_volume_fraction','balance_residual_m3'],'surge-swab':['maximum_mass_balance_residual_kg','maximum_reynolds','maximum_pipe_displacement_m','numerical_tolerance_met','time_step_s'], 'torque-drag':['hookload_n','surface_torque_nm','minimum_tension_n','surface_tension_margin_n','surface_torque_margin_nm','hookload_residual_n','torque_residual_nm']};
  const metrics=summaries[model].filter(k=>k in result);
  const y:Record<Model,[string[],number,string]>={
    dynamics:[[],1,'Simulated response'],
    'bit-condition':[['survival','approximate_lower','approximate_upper'],1,'Descriptive cohort survival fraction'],
    'wear-fatigue':[['initial_wall_m','predicted_wall_m','conservative_wall_m'],1,'Uniform wall thickness (m)'],
    anomaly:[[],1,'Balance replay'],
    'gas-phase':[['vapor_fraction'],1,'Supplied vapor mole fraction'],
    supervision:[[],1,'Software simulation'],buckling:[['compression_n','upper_compression_n','sinusoidal_threshold_n','helical_threshold_n'],1000,'Local compression and thresholds (kN)'],stability:[['hoop_effective_pa','axial_effective_pa','minimum_principal_pa'],1e6,'Effective stress (MPa)'],transport:[['fluid_velocity_m_s','settling_velocity_m_s','net_upward_velocity_m_s'],1,'Axial velocity (m/s)'],'surge-swab':[['minimum_gauge_pa','maximum_gauge_pa'],1e6,'Gauge pressure (MPa)'],'torque-drag':[['tension_n'],1000,'Axial tension (kN)']};
  const [keys,factor,yLabel]=y[model];const series=keys.map((key,i)=>({key,label:presentation(key)[0],color:palette[i]}));
  const cols=profile.length?Object.keys(profile[0]).filter(k=>typeof profile[0][k]==='number').slice(0,9).concat(model==='buckling'?['mode_indicator','uncertainty_mode_indicator']:[]):[];
  return <><div className="scope-note"><div><strong>{human(String(result.status))}</strong><p>{String(result.scope??'')} Approval issued: {String(result.approval_issued)}.{result.input_evidence_state?' Input evidence: '+human(String(result.input_evidence_state))+'.':''}</p></div></div>
    {(result.reasons as string[]|undefined)?.length?<div className="research-alert" role="status"><strong>Assessment conditions</strong><ul>{(result.reasons as string[]).map((reason,i)=><li key={i}>{reason}</li>)}</ul></div>:null}
    <div className="research-metrics">{metrics.map(k=>{const [label,factor]=presentation(k);return <div className="panel" key={k}><span>{label}</span><strong>{typeof result[k]==='number'?fmt(Number(result[k])/factor,6):fmt(result[k])}</strong></div>;})}</div>
    {model==='buckling'&&result.mode_counts&&<section className="panel"><div className="panel-heading"><div><h2>Local buckling indicators</h2><p>Selected-formulation susceptibility by retained profile point; these counts do not measure buckled length.</p></div></div><div className="research-metrics research-mode-counts">{Object.entries(result.mode_counts as Document).map(([key,value])=><div key={key}><span>{human(key)}</span><strong>{fmt(value,0)}</strong></div>)}</div></section>}
    {profile.length>0&&<section className="panel"><div className="panel-heading"><div><h2>{model==='stability'?'Wall stress around the borehole':model==='bit-condition'?'Censored cohort history':'Depth profile'}</h2><p>{profile.length} retained points · original inputs and complete results preserved in reports</p></div></div><Plot rows={model==='bit-condition'?[{drilling_hours:0,survival:1,approximate_lower:null,approximate_upper:null},...profile]:profile} step={model==='bit-condition'} range={model==='bit-condition'||model==='gas-phase'?[0,1]:undefined} xKey={model==='stability'?'angle_deg':model==='bit-condition'?'drilling_hours':'md_m'} xLabel={model==='stability'?'Circumferential angle (°)':model==='bit-condition'?'Drilling exposure (hours)':'Measured depth (m)'} series={series} factor={factor} yLabel={yLabel}/>
      {model==='surge-swab'&&<Plot rows={profile} xKey="md_m" xLabel="Measured depth (m)" series={[{key:'minimum_perturbation_pa',label:'Minimum change',color:palette[0]},{key:'maximum_perturbation_pa',label:'Maximum change',color:palette[1]}]} factor={1e6} yLabel="Pressure perturbation (MPa)"/>}
      {model==='transport'&&<Plot rows={profile} xKey="md_m" xLabel="Measured depth (m)" series={[{key:'final_volume_fraction',label:'Retained solids fraction',color:palette[2]}]} yLabel="Final cuttings volume fraction"/>}
      {model==='torque-drag'&&<Plot rows={profile} xKey="md_m" xLabel="Measured depth (m)" series={[{key:'torque_nm',label:'Torque',color:palette[1]}]} factor={1000} yLabel="Torque (kN·m)"/>}
      <details><summary>Inspect profile values · first 80 points</summary><div className="table-scroll"><table><thead><tr>{cols.map(k=><th key={k}>{presentation(k)[0]}</th>)}</tr></thead><tbody>{profile.slice(0,80).map((r,i)=><tr key={i}>{cols.map(k=><td key={k}>{typeof r[k]==='number'?fmt(Number(r[k])/presentation(k)[1],5):human(String(r[k]))}</td>)}</tr>)}</tbody></table></div></details></section>}
    {history.length>0&&<section className="panel"><div className="panel-heading"><h2>Retained response through time</h2></div>{historyPlots[model].map(([keys,factor,label],i)=><Plot key={i} rows={history} breakKey={model==='anomaly'?'quality_status':undefined} range={model==='supervision'&&i===1?[0,1]:undefined} xKey="time_s" xLabel="Elapsed time (s)" series={keys.map((key,j)=>({key,label:presentation(key)[0],color:palette[j]}))} factor={factor} yLabel={label}/>)}</section>}
    {model==='dynamics'&&result.mode_frequencies_hz&&<><EvidenceObject title="Simulated modes & numerical refinement" value={{mode_frequencies_hz:result.mode_frequencies_hz,refinement_relative_errors:result.refinement_relative_errors,observability:result.observability}}/><EvidenceTable title="Supplied native sensor channels" rows={(result.sensor_review??[]) as Document[]} columns={['name','axis','units','status','minimum_sampling_hz','anti_alias_bandwidth_hz','rms','bandwidth_eligible_modes','modal_observability_established']}/></>}
    {model==='dynamics'&&((result.sensor_review??[]) as Document[]).map((sensor,i)=><section className="panel" key={i}><div className="panel-heading"><div><h2>{String(sensor.name)} · supplied native samples</h2><p>{String(sensor.status)} · {sensorUnit(sensor.units)} · calibration is supplied, not independently verified.</p></div></div><Plot rows={((sensor.samples??[]) as Document[]).map(row=>({...row,value:row.quality==='accepted'?row.value:null}))} xKey="time_s" xLabel="Native sample time (s)" series={[{key:'value',label:'Supplied '+human(String(sensor.axis)),color:palette[0]}]} yLabel={sensorUnit(sensor.units)}/></section>)}
    {model==='bit-condition'&&<><EvidenceTable title="Inspected run records" rows={(result.run_records??[]) as Document[]} columns={['run_id','well','bit_serial','formation','drilling_hours','drilled_m','average_rop_m_h','termination','inspection_grade','included_in_cohort']}/><EvidenceObject title="Conditional cost comparison" value={result.cost_comparison}/></>}
    {model==='wear-fatigue'&&<><EvidenceObject title="Separate fatigue exposure" value={result.fatigue}/><EvidenceObject title="Restricted residual-wall strength scenario" value={result.residual_strength}/></>}
    {model==='anomaly'&&<><EvidenceTable title="Causal balance-anomaly candidates" rows={(result.candidate_events??[]) as Document[]} columns={['onset_s','alarm_s','end_s','sign']}/><EvidenceObject title="Supplied event replay evaluation" value={result.event_evaluation}/></>}
    {model==='gas-phase'&&<EvidenceObject title="Characterized binary equilibrium" value={result.equilibrium}/>}
    {model==='supervision'&&<><EvidenceTable title="Simulation request audit · first 80 records" rows={(result.request_audit??[]) as Document[]} columns={['request_id','at_s','accepted_in_simulation','reasons','equipment_command_issued']}/><EvidenceObject title="Supplied request examples" value={result.request_example_audit}/></>}
    {model==='buckling'&&result.load_transfer&&<section className="panel research-transfer"><div className="panel-heading"><h2>Conditional load transfer</h2></div><p>{human(String((result.load_transfer as Document).status))} · Prescribed interval bottom force; this does not set a surface or bit WOB limit.</p>{['upper_effective_tension_n','unbuckled_upper_effective_tension_n','upper_tension_change_n','final_refinement_change_n'].filter(k=>k in (result.load_transfer as Document)).map(k=><p key={k}>{presentation(k)[0]}: {fmt(Number((result.load_transfer as Document)[k])/1000,6)}</p>)}<Plot rows={((result.load_transfer as Document).profile??[]) as Document[]} xKey="md_m" xLabel="Measured depth (m)" series={[{key:'effective_tension_n',label:'Conditional effective tension',color:palette[0]}]} factor={1000} yLabel="Axial tension (kN)"/></section>}
    <section className="panel"><details><summary>Numerical checks, source references & applicability</summary><pre className="research-json">{JSON.stringify(preview(Object.fromEntries(Object.entries(result).filter(([k])=>!['profile','history'].includes(k)).map(([k,v])=>[k,k==='load_transfer'?Object.fromEntries(Object.entries(v as Document).filter(([sub])=>sub!=='profile')):v]))),null,2)}</pre></details></section>
    {(result.limitations as string[]|undefined)?.length?<div className="scope-note"><div><strong>Interpretation limits</strong><ul>{(result.limitations as string[]).map((s,i)=><li key={i}>{s}</li>)}</ul></div></div>:null}
  </>;
}
export function ResearchStudy({model,project,online,onError,onNotice}:Props){
  const base='/projects/'+project.id;
  const [revisions,setRevisions]=useState<Revision[]>([]),[schemas,setSchemas]=useState<Record<Model,Schema>|null>(null),[form,setForm]=useState<Document|null>(null),[history,setHistory]=useState<Study[]>([]),[hydraulics,setHydraulics]=useState<Study[]>([]),[result,setResult]=useState<Study|null>(null),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false);
  const inputFile=useRef<HTMLInputElement>(null);const resultView=useRef<HTMLDivElement>(null);const generation=useRef(0);
  const importsAvailable=['dynamics','bit-condition','wear-fatigue','anomaly','gas-phase','supervision'].includes(model);
  const hydraulicLinked=model==='transport'||model==='surge-swab';
  const linked=hydraulicLinked||model==='buckling';
  const linkKey=hydraulicLinked?'hydraulics_calculation_id':'torque_drag_calculation_id';
  const sourceModel=hydraulicLinked?'hydraulics':'torque-drag';
  useEffect(()=>{let active=true;Promise.all([api<Revision[]>(base+'/engineering-revisions?module=M1'),api<Record<Model,Schema>>('/research/schemas'),api<Study[]>(base+'/calculations?model='+model),linked?api<Study[]>(base+'/calculations?model='+sourceModel):Promise.resolve([])]).then(async([r,s,h,hy])=>{
    const draft=r.length?await api<Document>(base+'/research/'+model+'/template/'+r[0].id):null;
    if(active){if(draft&&linked)draft[linkKey]=hy.find(c=>c.inputs_si.geometry_revision_id===r[0]?.id)?.id??'';setRevisions(r);setSchemas(s);setHistory(h);setHydraulics(hy);setForm(draft);}
  }).catch(e=>{if(active)onError(e.message);});return()=>{active=false;generation.current++;};},[base,model,linked,linkKey,sourceModel]);
  useEffect(()=>{if(!result)return;const frame=requestAnimationFrame(()=>resultView.current?.scrollIntoView({block:'start'}));return()=>cancelAnimationFrame(frame);},[result?.id]);
  const update=(key:string,v:Value)=>{setForm(f=>f?{...f,[key]:v,...(key!=='evidence_state'&&key!=='study_name'&&f.evidence_state==='supplied'?{evidence_state:'unknown'}:{})}:f);setDirty(true);};
  const load=async(id:string)=>{const seq=++generation.current;setBusy(true);try{const draft=await api<Document>(base+'/research/'+model+'/template/'+id);if(seq!==generation.current)return;if(linked)draft[linkKey]=hydraulics.find(c=>c.inputs_si.geometry_revision_id===id)?.id??'';setForm(draft);setResult(null);setDirty(true);onNotice('Draft assumptions loaded. Review the evidence state and all inputs.');}catch(e){onError((e as Error).message);}finally{if(seq===generation.current)setBusy(false);}};
  return <><div className="scope-note"><div><strong>{descriptions[model][0]}</strong><p>{descriptions[model][1]}</p></div></div>
    {!revisions.length?<section className="panel"><h2>Save well geometry first</h2><p>This study requires an immutable M1 geometry revision and accepted directional survey.</p></section>:null}
    {form&&importsAvailable&&<section className="panel"><div className="panel-heading"><div><h2>Preserve study input JSON</h2><p>Import complete typed SI inputs, including native samples and external phase studies. The original file and SHA-256 are retained.</p></div></div><div className="research-import"><input ref={inputFile} type="file" aria-label="Study input JSON" accept=".json,application/json" disabled={busy||!online} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);onError('');try{if(file.size>2*1024*1024)throw new Error('Study input file exceeds 2 MiB.');const body=new FormData();body.append('file',file);const imported=await api<{inputs_si:Document;source_sha256:string}>(base+'/research/'+model+'/imports',{method:'POST',body});setForm(imported.inputs_si);setResult(null);setDirty(true);onNotice('Original SI input document preserved. Review evidence and calculate to save a study.');}catch(error){onError((error as Error).message);}finally{setBusy(false);if(inputFile.current)inputFile.current.value='';}}}/><button type="button" className="button secondary" onClick={()=>{const blob=new Blob([JSON.stringify({...form,input_dataset_id:null},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=model+'-study-inputs-SI.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Download current inputs · SI JSON</button></div>{form.input_dataset_id&&<p className="well-note">Preserved input document: {String(form.input_dataset_id)}. Edits are compared with the original in the saved result.</p>}</section>}
    {form&&schemas&&<section className="panel"><div className="panel-heading"><div><h2>Study inputs & evidence</h2><p>Pressure and force fields display engineering units; saved inputs use SI units. Supplied evidence resets to unknown when assumptions change.</p></div><button className="button secondary" disabled={busy||!online} onClick={()=>load(String(form.geometry_revision_id))}>Reset draft assumptions</button></div>
      <form onSubmit={async e=>{e.preventDefault();setBusy(true);onError('');try{const saved=await api<Study>(base+'/calculations/'+model,{method:'POST',body:JSON.stringify(form)});setResult(saved);setHistory(h=>[saved,...h]);setDirty(false);onNotice('Immutable study saved with geometry, evidence and numerical checks.');}catch(e){onError((e as Error).message);}finally{setBusy(false);}}}>
      <fieldset disabled={busy||!online} className="research-fields">
      <div className="lab-fields"><label className="field-label">Geometry context<select value={String(form.geometry_revision_id)} onChange={e=>load(e.target.value)}>{revisions.map(r=><option key={r.id} value={r.id}>{r.id.slice(0,8)+' · '+r.change_note}</option>)}</select></label><label className="field-label">Declared MD datum<input required value={String(form.depth_datum)} onChange={e=>update('depth_datum',e.target.value)}/></label>
      {Object.entries(schemas[model].properties??{}).filter(([k])=>!['input_dataset_id','geometry_revision_id','depth_datum','hydraulics_calculation_id','torque_drag_calculation_id'].includes(k)&&!(model==='gas-phase'&&(form.mode==='native_binary_flash'?['external_model_reference','external_review_state','external_review_note','external_points','total_gas_inventory_mol','initial_dissolved_gas_mol','mass_transfer_time_s','replay_step_s','balance_tolerance_mol']:['components','binary_interaction','absolute_pressure_pa','temperature_k']).includes(k))).map(([k,s])=><Field key={k} name={k} schema={s} root={schemas[model]} value={form[k]??null} required={schemas[model].required?.includes(k)} onChange={v=>update(k,v)}/>)}
      </div>
      {linked&&<div className="research-link"><label className="field-label">{hydraulicLinked?'Saved hydraulic source':'Saved torque & drag source'}<select required value={String(form[linkKey]??'')} onChange={e=>update(linkKey,e.target.value)}><option value="">Choose a study with this geometry</option>{hydraulics.filter(h=>h.inputs_si.geometry_revision_id===form.geometry_revision_id).map(h=><option key={h.id} value={h.id}>{String(h.inputs_si.study_name)+' · '+h.id.slice(0,8)+' · '+String(h.result.status)}</option>)}</select></label>{hydraulicLinked&&project.origin==='synthetic'&&<button type="button" className="button secondary" onClick={async()=>{setBusy(true);try{const source=await api<Study>(base+'/research/source-hydraulics/'+form.geometry_revision_id,{method:'POST'});setHydraulics(h=>[source,...h]);update('hydraulics_calculation_id',source.id);onNotice('Synthetic Newtonian hydraulic source created and linked.');}catch(e){onError((e as Error).message);}finally{setBusy(false);}}}>Create synthetic hydraulic source</button>}<p>{hydraulicLinked?'The saved source supplies fluid properties, geometry state, flow and pressure windows.':'The saved M10 source supplies string dimensions, buoyed weight, friction, operation and the local effective-force baseline. Save a source in Torque & drag first.'} Original inputs and source hash remain bound to this study.</p></div>}
      <button className="button primary" type="submit">{busy?'Calculating…':'Calculate & save study'}</button></fieldset></form></section>}
    {result&&<div ref={resultView} className="research-result"><div className="panel-heading"><div><h2>{String(result.inputs_si.study_name)}</h2><p>{result.id} · {new Date(result.created_at).toLocaleString()} {dirty?'· draft edited; result retains saved inputs':''}</p></div></div><Result model={model} result={result.result}/></div>}
    <section className="panel"><div className="panel-heading"><div><h2>Saved studies</h2><p>Reopen the exact inputs and results. Editing a saved study creates a new record.</p></div></div>{history.length?<div className="research-history">{history.map(h=><button key={h.id} className="button secondary" disabled={busy} onClick={()=>{setResult(h);setForm(structuredClone(h.inputs_si));setDirty(false);onNotice('Saved study reopened.');}}><span>{String(h.inputs_si.study_name)}</span><small>{human(String(h.result.status))} · {h.id.slice(0,8)}</small></button>)}</div>:<p>No studies saved for this module yet.</p>}</section>
  </>;
}
