import {useEffect,useState} from 'react';
import {api} from './api';
import type {Revision} from './GeometryWorkspace';
type Source={id:string;kind:string;filename:string;metadata:Record<string,unknown>};
type Scenario={bulk_shale_volume:number;total_porosity:number;primary_porosity_bulk:number;quartz_grain_fraction:number;volume_balance_residual:number;porosity_residual:number;texture_nonunique:boolean;laminated_range:number[];restricted_scenario:{branch:string;laminated_bulk:number;dispersed_bulk:number;structural_bulk:number;nonlaminated_host_fraction:number;primary_porosity_host_normalized:number|null};coexistence_family:unknown[]};
type Sample={source_index:number;depth_m:number;status:string;reason:string;scenario:Scenario|null;sensitivity:{tested_admissible_corners:number;tested_outside_corners:number;restricted_branches:string[];tested_ranges:Record<string,number[]>}|null};
type Analysis={id:string;created_at:string;inputs_si:Record<string,unknown>;result:{status:string;reason:string;eligible_count:number;withheld_count:number;ambiguous_count:number;geometry_revision_id:string;source_sha256:string;warnings:string[];rows:Sample[];model_grid:{branch:string;shale_volume:number;primary_porosity:number;total_porosity:number}[]}};
const fmt=(n:number|null|undefined,d=4)=>n==null?'—':n.toLocaleString('en-US',{maximumFractionDigits:d});
const initial:Record<string,string>={study:'',datum:'',phiCurve:'',phiUnit:'V/V',phiUncertainty:'0',phiNote:'',shaleCurve:'',shaleUnit:'V/V',method:'supplied_volume',shaleUncertainty:'0',calibration:'',sandPhi:'.3',shalePhi:'.15',sandDelta:'0',shaleDelta:'0',grClean:'20',grShale:'100',grCleanDelta:'0',grShaleDelta:'0',endpointSource:'',convention:'',correction:'unknown',correctionNote:'',quality:'',alignment:'',mineral:''};
const branchColors:Record<string,string>={laminated:'#216f5d',laminated_dispersed:'#b57524',laminated_structural:'#647db1'};
export function ShalySand({project,online,onError,onNotice}:{project:{id:string;datum:string;origin:string};online:boolean;onError:(s:string)=>void;onNotice:(s:string)=>void}){
  const base='/projects/'+project.id;
  const [form,setForm]=useState<Record<string,string>>({...initial,datum:project.datum}),[sources,setSources]=useState<Source[]>([]),[source,setSource]=useState(''),[curves,setCurves]=useState<{mnemonic:string;unit:string}[]>([]);
  const [revisions,setRevisions]=useState<Revision[]>([]),[revision,setRevision]=useState(''),[history,setHistory]=useState<Analysis[]>([]),[result,setResult]=useState<Analysis|null>(null),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false);
  const set=(name:string,value:string)=>{setForm(v=>({...v,[name]:value}));setDirty(true);};
  useEffect(()=>{let active=true;Promise.all([api<Revision[]>(base+'/engineering-revisions?module=M1'),api<Source[]>(base+'/datasets'),api<Analysis[]>(base+'/calculations?model=shaly_sand')]).then(([r,s,h])=>{if(active){setRevisions(r);setRevision(r[0]?.id??'');setSources(s.filter(d=>d.kind==='las'));setSource(s.find(d=>d.kind==='las')?.id??'');setHistory(h);}}).catch(e=>{if(active)onError(e.message);});return()=>{active=false;};},[base]);
  useEffect(()=>{let active=true;setCurves([]);setDirty(true);if(source)api<Source>(base+'/datasets/'+source).then(s=>{if(active){const curves=(s.metadata.curves as {mnemonic:string;unit:string}[]).slice(1);setCurves(curves);const p=curves.find(c=>c.mnemonic==='PHIT')??curves.find(c=>['V/V','PU','%'].includes(c.unit));const v=curves.find(c=>c.mnemonic==='VSH');const gr=curves.find(c=>c.unit==='API');setForm(f=>({...f,phiCurve:p?.mnemonic??'',phiUnit:p?.unit??'V/V',shaleCurve:v?.mnemonic??gr?.mnemonic??'',shaleUnit:v?.unit??gr?.unit??'V/V',method:v?'supplied_volume':'linear_gr'}));}}).catch(e=>{if(active)onError(e.message);});return()=>{active=false;};},[source,base]);
  const example=async()=>{setBusy(true);try{const imported=await api<{id:string}>(base+'/examples/shaly-sand',{method:'POST'});setSources((await api<Source[]>(base+'/datasets')).filter(d=>d.kind==='las'));setSource(imported.id);setForm({...initial,datum:project.datum,study:'Synthetic Thomas-Stieber volume scenarios',phiCurve:'PHIT',shaleCurve:'VSH',phiNote:'Generated total physical porosity; no apparent sonic/neutron conversion',calibration:'Generated known wet-shale bulk volumes',endpointSource:'Synthetic software reference: sand 0.30, shale 0.15 porosity',convention:'Bulk-rock total = primary pores + wet-shale volume times shale porosity',correction:'synthetic',correctionNote:'Generated compatible fractions; no field corrections',quality:'Synthetic observations; no core or image-log validation',alignment:'Generated MD aligned with demonstration survey; no tool offset',mineral:'Constant quartz framework; same wet-shale properties in all textures'});setDirty(true);onNotice('Synthetic shaly-sand LAS source loaded with explicit model assumptions.');}catch(e){onError((e as Error).message);}finally{setBusy(false);}};
  const text=(name:string,label:string,area=false)=><label className="field-label" key={name}>{label}{area?<textarea required minLength={3} maxLength={400} value={form[name]} onChange={e=>set(name,e.target.value)}/>:<input required value={form[name]} onChange={e=>set(name,e.target.value)} maxLength={name==='study'?100:400}/>}</label>;
  const numeric=(name:string,label:string,min:number,max:number)=><label className="field-label" key={name}>{label}<input required type="number" step="any" min={min} max={max} value={form[name]} onChange={e=>set(name,e.target.value)}/></label>;
  const curve=(name:string,label:string,filter:(u:string)=>boolean)=><label className="field-label">{label}<select required value={form[name]} onChange={e=>{const c=curves.find(c=>c.mnemonic===e.target.value)!;setForm(f=>({...f,[name]:c.mnemonic,[name==='phiCurve'?'phiUnit':'shaleUnit']:c.unit}));setDirty(true);}}><option value="">Select compatible source curve</option>{curves.filter(c=>filter(c.unit)).map(c=><option value={c.mnemonic} key={c.mnemonic}>{c.mnemonic+' ['+c.unit+']'}</option>)}</select></label>;
  return <><div className="scope-note"><div><strong>M4 · Thomas–Stieber interpretation scenarios</strong><p>Compare laminated, dispersed and structural volume scenarios with declared endmembers. Coexisting textures remain visible. These calculations require compatible total porosity; apparent sonic/neutron porosity is not substituted.</p></div></div>
  <div className="panel shaly-editor"><div className="panel-heading"><div><h2>Source, endpoints & interpretation evidence</h2><p>Native MD sampling; wet-shale bulk volumes; primary and total porosity distinguished.</p></div>{project.origin==='synthetic'&&<button className="button secondary" onClick={example} disabled={busy||!online}>Load synthetic shaly-sand example</button>}</div>
    <form onSubmit={async e=>{e.preventDefault();setBusy(true);onError('');try{const num=(k:string)=>Number(form[k]);const inputs={study_name:form.study,dataset_id:source,geometry_revision_id:revision,depth_datum:form.datum,
      porosity:{curve:form.phiCurve,unit:form.phiUnit,basis:'total',uncertainty:num('phiUncertainty'),source_note:form.phiNote},
      shale_indicator:{curve:form.shaleCurve,unit:form.shaleUnit,method:form.method,uncertainty:num('shaleUncertainty'),calibration_note:form.calibration},
      endpoints:{sand_porosity:num('sandPhi'),shale_porosity:num('shalePhi'),sand_porosity_uncertainty:num('sandDelta'),shale_porosity_uncertainty:num('shaleDelta'),gr_clean_api:num('grClean'),gr_shale_api:num('grShale'),gr_clean_uncertainty_api:num('grCleanDelta'),gr_shale_uncertainty_api:num('grShaleDelta'),source_note:form.endpointSource,porosity_convention_note:form.convention},
      correction_status:form.correction,correction_note:form.correctionNote,acquisition_quality_note:form.quality,depth_alignment_note:form.alignment,mineral_fluid_note:form.mineral};
      const saved=await api<Analysis>(base+'/calculations/shaly-sand',{method:'POST',body:JSON.stringify(inputs)});setResult(saved);setDirty(false);setHistory(await api<Analysis[]>(base+'/calculations?model=shaly_sand'));onNotice('Shaly-sand scenarios, alternative textures, sensitivity and source hashes saved.');}catch(e){onError((e as Error).message);}finally{setBusy(false);}}}>
    <div className="lab-fields">{text('study','Study name')}<label className="field-label">LAS source<select required value={source} onChange={e=>{setSource(e.target.value);setForm(f=>({...f,correction:'unknown',phiNote:'',calibration:'',correctionNote:'',quality:'',alignment:'',mineral:''}));setDirty(true);}}><option value="">Select a source</option>{sources.map(s=><option key={s.id} value={s.id}>{s.filename}</option>)}</select></label><label className="field-label">Geometry context<select required value={revision} onChange={e=>{setRevision(e.target.value);setDirty(true);}}><option value="">Save M1 geometry first</option>{revisions.map(r=><option key={r.id} value={r.id}>{r.id.slice(0,8)+' · '+r.change_note}</option>)}</select></label>{text('datum','Declared log MD datum')}{curve('phiCurve','Total physical porosity curve',u=>['V/V','PU','%'].includes(u))}<label className="field-label">Shale-volume mapping<select value={form.method} onChange={e=>{set('method',e.target.value);set('shaleCurve','');}}><option value="supplied_volume">Supplied wet-shale bulk volume</option><option value="linear_gr">Supplied linear GR calibration</option></select></label>{curve('shaleCurve','Shale indicator curve',u=>form.method==='linear_gr'?u==='API':['V/V','PU','%'].includes(u))}{numeric('phiUncertainty','Porosity observation perturbation ('+form.phiUnit+')',0,form.phiUnit==='V/V'?.2:20)}{numeric('shaleUncertainty','Shale indicator perturbation ('+form.shaleUnit+')',0,200)}{text('phiNote','Total porosity measurement / derivation evidence',true)}{text('calibration','Shale-volume calibration evidence',true)}</div>
    <div className="editor-section-heading"><h3>Endmember assumptions & sensitivity</h3></div><div className="lab-fields">{numeric('sandPhi','Clean-sand framework porosity (fraction)',.001,.65)}{numeric('shalePhi','Wet-shale endmember porosity (fraction)',0,.65)}{numeric('sandDelta','Sand-porosity endpoint perturbation (± fraction)',0,.2)}{numeric('shaleDelta','Shale-porosity endpoint perturbation (± fraction)',0,.2)}{form.method==='linear_gr'&&<>{numeric('grClean','Clean-sand GR endpoint (API)',0,1000)}{numeric('grShale','Shale GR endpoint (API)',0,1000)}{numeric('grCleanDelta','Clean GR endpoint perturbation (± API)',0,200)}{numeric('grShaleDelta','Shale GR endpoint perturbation (± API)',0,200)}</>}{text('endpointSource','Endmember source / version',true)}{text('convention','Porosity and bound-water convention',true)}<label className="field-label">Tool / environmental correction state<select value={form.correction} onChange={e=>set('correction',e.target.value)}><option value="unknown">Unknown — interpretation withheld</option><option value="raw">Raw — interpretation withheld</option><option value="supplied_corrected">Supplied corrected, compatible curves</option>{project.origin==='synthetic'&&<option value="synthetic">Synthetic compatible fractions</option>}</select></label>{text('correctionNote','Correction evidence',true)}{text('quality','Acquisition / borehole quality evidence',true)}{text('alignment','Depth alignment and tool-response evidence',true)}{text('mineral','Mineral and fluid assumptions',true)}</div>
    <div className="lab-action"><button className="button primary" disabled={busy||!online||!revision||!form.phiCurve||!form.shaleCurve}>{busy?'Calculating…':'Run & save interpretation scenarios'}</button><p className="small-note">Up to 1,000 native samples. Endmember perturbations are tested corners, not confidence intervals.</p></div>
    </form></div>
    {result&&<div className="panel shaly-result"><div className="panel-heading"><div><h2>{String(result.inputs_si.study_name)} <span className="badge amber">{result.result.status.replaceAll('_',' ')}</span></h2><p>{result.result.reason}</p></div></div>{dirty&&<p className="inset-note">This result retains its saved inputs. Current form edits have not been calculated.</p>}<div className="lab-fields"><p>Eligible scenarios <strong>{result.result.eligible_count}</strong></p><p>Withheld / outside model <strong>{result.result.withheld_count}</strong></p><p>Nonunique textures <strong>{result.result.ambiguous_count}</strong></p></div><ShalyPlot result={result.result}/>
    <div className="table-scroll"><table><thead><tr><th>MD (m)</th><th>State</th><th>Restricted scenario</th><th>Primary porosity, bulk</th><th>Quartz grain volume</th><th>Laminated / dispersed / structural, bulk</th><th/></tr></thead><tbody>{result.result.rows.slice(0,100).map(r=><tr key={r.source_index}><td>{fmt(r.depth_m,1)}</td><td title={r.reason}>{r.status.replaceAll('_',' ')}</td><td>{r.scenario?.restricted_scenario.branch.replaceAll('_',' ')??'—'}</td><td>{fmt(r.scenario?.primary_porosity_bulk)}</td><td>{fmt(r.scenario?.quartz_grain_fraction)}</td><td>{r.scenario?[r.scenario.restricted_scenario.laminated_bulk,r.scenario.restricted_scenario.dispersed_bulk,r.scenario.restricted_scenario.structural_bulk].map(v=>fmt(v)).join(' / '):'—'}</td><td><details><summary>Alternatives & sensitivity</summary><p>{r.reason}</p><pre>{JSON.stringify({scenario:r.scenario,sensitivity:r.sensitivity},null,2)}</pre></details></td></tr>)}</tbody></table></div><p className="small-note">First 100 samples shown. The nonlaminated host fraction is not net pay. A branch match does not prove geological topology, connectivity or permeability.</p>
    <details className="inset-note"><summary>Preserved inputs and source evidence</summary><pre>{JSON.stringify({inputs:result.inputs_si,source_sha256:result.result.source_sha256,geometry_revision:result.result.geometry_revision_id},null,2)}</pre></details><div className="inset-note">{result.result.warnings.map(w=><p key={w}>{w}</p>)}</div></div>}
    <div className="panel"><div className="panel-heading"><div><h2>Preserved interpretation studies</h2><p>Reports include the full native-depth scenarios and their applicability states.</p></div></div><div className="table-scroll"><table><thead><tr><th>Study</th><th>Geometry</th><th>Eligible / withheld</th><th>State</th><th/></tr></thead><tbody>{history.map(h=><tr key={h.id}><td>{String(h.inputs_si.study_name)}</td><td>{h.result.geometry_revision_id.slice(0,8)}</td><td>{h.result.eligible_count+' / '+h.result.withheld_count}</td><td>{h.result.status.replaceAll('_',' ')}</td><td><button className="text-button" onClick={()=>{setResult(h);setDirty(true);}}>Open saved study</button></td></tr>)}</tbody></table></div></div></>;
}
function ShalyPlot({result}:{result:Analysis['result']}){
  const max=Math.ceil(Math.max(.4,...result.model_grid.map(p=>p.total_porosity))/.05)*.05,x=(v:number)=>60+v*500,y=(p:number)=>300-p/max*260;
  return <div className="shaly-plots">{(['primary_porosity','total_porosity'] as const).map(basis=><div key={basis}><h3>{basis==='primary_porosity'?'Primary-pore volume crossplot':'Total physical porosity crossplot'}</h3><svg viewBox="0 0 600 350" role="img" aria-label={basis.replaceAll('_',' ')+' versus bulk wet-shale fraction; scenario points with three endmember branches'}>{[0,1,2,3,4,5].map(i=><g key={i}><line x1="60" x2="560" y1={y(max*i/5)} y2={y(max*i/5)} stroke="#dae2d5"/><text x="52" y={y(max*i/5)+4} fontSize="11" textAnchor="end">{fmt(max*i/5,2)}</text><text x={x(i/5)} y="320" fontSize="11" textAnchor="middle">{fmt(i/5,1)}</text></g>)}{['laminated','dispersed','structural'].map(branch=><polyline key={branch} points={result.model_grid.filter(p=>p.branch===branch).map(p=>x(p.shale_volume)+','+y(p[basis])).join(' ')} fill="none" stroke={branchColors[branch==='laminated'?branch:'laminated_'+branch]} strokeWidth="2"/>)}{result.rows.filter(r=>r.scenario).map(r=>{const s=r.scenario!;return <circle key={r.source_index} cx={x(s.bulk_shale_volume)} cy={y(basis==='primary_porosity'?s.primary_porosity_bulk:s.total_porosity)} r="4" fill={branchColors[s.restricted_scenario.branch]} stroke="white"><title>{'MD '+r.depth_m+' m · '+r.status+' · '+s.restricted_scenario.branch}</title></circle>;})}<text x="60" y="343" fontSize="11">Bulk wet-shale fraction → · porosity is a fraction</text></svg></div>)}<p className="small-note">Green: laminated · Amber: dispersed · Blue: structural. Curves show pure endmember branches; points may have many coexisting-texture alternatives.</p></div>;
}
