import {useEffect, useRef, useState} from 'react';
import {api} from './api';
import type {Revision} from './GeometryWorkspace';
import type {SurveySource} from './DirectionalWorkspace';
import type {ProjectTreeData, WellboreModel, WellModel} from './components/ProjectTree';

export type TrajectoryRole = 'planned'|'actual'|'scenario';
type Freshness = {stale:boolean;reasons:string[]};
type Frame = {datum:string;north_reference:string;coordinate_reference:string;wellhead_north_m:number;wellhead_east_m:number;wellhead_elevation_m:number};
export type SourceRevision = {id:string;kind:string;revision_no:number;trajectory_type:TrajectoryRole;sha256:string;created_at:string;frame:Frame;evidence_state:string;survey_quality_note:string;tool_metadata:Record<string,unknown>};
export type SavedTrajectory = Revision & SourceRevision & {survey_revision_id:string};
type SavedDiagnostic = SourceRevision & {envelope:{status:string;model:string;result:Record<string,unknown>}};
export type WellboreContext = {project_id:string;wellbore:WellboreModel;well:WellModel;trajectory_type:TrajectoryRole;survey_source:(SurveySource & {kind:string;row_count:number;created_at:string;event_count:number;metadata:Record<string,unknown>})|null;active:{survey:SourceRevision|null;trajectory:SavedTrajectory|null;uncertainty:SavedDiagnostic|null;proximity:SavedDiagnostic|null};freshness:Record<string,Freshness>;comparison_state:Partial<Record<TrajectoryRole,Freshness & {revision_id:string;revision_no:number}>>;revisions:{id:string;kind:string;trajectory_type:TrajectoryRole;revision_no:number;created_at:string;sha256:string}[]};
type Props = {context:WellboreContext;datasets:{id:string;kind:string;filename:string}[];datum:string;northReference:string;onRefresh:()=>void;onError:(s:string)=>void;onRole:(role:TrajectoryRole)=>void;onSelectMD:(md:number)=>void;selectedMD:number|null};
const roles:TrajectoryRole[]=['planned','actual','scenario'];
const sample=JSON.stringify({stations:[{md_m:0,inclination_rad:0,azimuth_rad:0},{md_m:500,inclination_rad:.2,azimuth_rad:.5},{md_m:1000,inclination_rad:.3,azimuth_rad:.5}]},null,2);
const object=(text:string)=>{const value:unknown=JSON.parse(text);if(!value||Array.isArray(value)||typeof value!=='object')throw new Error('Metadata must be a JSON object.');return value;};
const fmt=(n:number)=>n.toLocaleString('en-US',{maximumFractionDigits:2});

export function WellboreWorkspace({context,datasets,datum,northReference,onRefresh,onError,onRole,onSelectMD,selectedMD}:Props){
  const {active,wellbore,trajectory_type:role}=context;
  const base='/v1/wellbores/'+wellbore.id;
  const [busy,setBusy]=useState(false),[mode,setMode]=useState('authored'),[file,setFile]=useState<File|null>(null),[dataset,setDataset]=useState('');
  const [stationText,setStationText]=useState(sample),[note,setNote]=useState(''),[quality,setQuality]=useState(active.survey?.survey_quality_note??''),[evidence,setEvidence]=useState(active.survey?.evidence_state??(role==='actual'?'synthetic':'authored_design'));
  const [frame,setFrame]=useState<Frame>(active.survey?.frame??{datum,north_reference:northReference,coordinate_reference:'',wellhead_north_m:0,wellhead_east_m:0,wellhead_elevation_m:0});
  const [toolMetadata,setToolMetadata]=useState(JSON.stringify(active.survey?.tool_metadata??{},null,2)),[uncertaintyMetadata,setUncertaintyMetadata]=useState('{}'),[geomagnetic,setGeomagnetic]=useState('{}'),[correlation,setCorrelation]=useState('independent');
  const [historical,setHistorical]=useState<{revision:unknown;freshness:Freshness}|null>(null),[historyId,setHistoryId]=useState('');
  const [comparisons,setComparisons]=useState<SavedTrajectory[]>([]),[visibility,setVisibility]=useState<Record<TrajectoryRole,boolean>>({planned:true,actual:true,scenario:false});
  const [offsets,setOffsets]=useState<WellboreModel[]>([]),[offsetId,setOffsetId]=useState(''),[offsetTrajectories,setOffsetTrajectories]=useState<SavedTrajectory[]>([]),[offsetRevision,setOffsetRevision]=useState('');
  useEffect(()=>{let live=true;
    Promise.all([api<SavedTrajectory[]>(base+'/trajectories'),api<ProjectTreeData>('/v1/projects/'+context.project_id+'/tree')]).then(([revisions,tree])=>{
      if(!live)return;setComparisons(roles.map(r=>revisions.find(v=>v.trajectory_type===r)).filter((v):v is SavedTrajectory=>!!v));
      setOffsets([...tree.fields.flatMap(f=>f.wells),...tree.unassigned_wells].flatMap(w=>w.wellbores).filter(w=>w.id!==wellbore.id));
    }).catch(e=>{if(live)onError(e.message);});return()=>{live=false;};
  },[base,context.project_id,context.revisions.length]);
  useEffect(()=>{let live=true;setOffsetRevision('');setOffsetTrajectories([]);if(offsetId)api<SavedTrajectory[]>('/v1/wellbores/'+offsetId+'/trajectories').then(rs=>{if(live)setOffsetTrajectories(rs);}).catch(e=>{if(live)onError(e.message);});return()=>{live=false;};},[offsetId]);
  useEffect(()=>{let live=true;setHistorical(null);if(historyId)api<{revision:unknown;freshness:Freshness}>(base+'/revisions/'+historyId).then(r=>{if(live)setHistorical(r);}).catch(e=>{if(live)onError(e.message);});return()=>{live=false;};},[base,historyId]);
  const mounted=useRef(true);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
  const mutate=async(path:string,body:unknown)=>{setBusy(true);onError('');try{await api(base+path,{method:'POST',body:body instanceof FormData?body:JSON.stringify(body)});onRefresh();}catch(e){if(mounted.current)onError((e as Error).message);}finally{if(mounted.current)setBusy(false);}};
  const saveSource=(event:React.FormEvent)=>{event.preventDefault();try{
    const metadata={trajectory_type:role,base_revision_id:active.survey?.id??null,change_note:note,frame,evidence_state:evidence,survey_quality_note:quality,tool_metadata:object(toolMetadata)};
    if(mode==='csv'){if(!file)throw new Error('Choose the original CSV file.');const data=new FormData();data.append('metadata',JSON.stringify(metadata));data.append('file',file);void mutate('/surveys/import',data);}
    else if(mode==='adopt'){if(!dataset)throw new Error('Choose a project source to explicitly adopt.');void mutate('/surveys/from-dataset',{...metadata,dataset_id:dataset});}
    else void mutate('/surveys',{...metadata,survey:object(stationText)});
  }catch(e){onError((e as Error).message);}};
  const diagnostic=(kind:'uncertainty'|'proximity')=>{const value=active[kind];return value&&<div><p className="alert warning">Saved {kind} · {value.envelope.status} · {context.freshness[kind]?.stale?'STALE dependencies':'bound to saved dependencies'} · no drilling clearance</p>{context.freshness[kind]?.reasons.map(s=><p key={s}>{s}</p>)}<details><summary>Saved calculation evidence</summary><pre>{JSON.stringify(value,null,2)}</pre></details></div>;};
  return <>
    <div className="panel"><div className="panel-heading"><div><h2>{wellbore.name} · saved directional revisions</h2><p>{context.well.name} · {role} · source evidence remains explicitly declared</p></div><label className="field-label">Trajectory role<select aria-label="Trajectory role" disabled={busy} value={role} onChange={e=>onRole(e.target.value as TrajectoryRole)}>{roles.map(r=><option key={r}>{r}</option>)}</select></label></div>
      <button className="button secondary" disabled={busy} onClick={onRefresh}>Reload saved revisions</button>
      <p>{active.survey?'Survey revision '+active.survey.revision_no+' · '+active.survey.evidence_state:'No source revision in this role.'} · {active.trajectory?'Trajectory revision '+active.trajectory.revision_no:'No saved trajectory'}</p>
      {context.freshness.trajectory?.stale&&<p role="status" className="alert warning">STALE trajectory: a newer source revision exists. Recalculate to create a new immutable trajectory.</p>}
      <button className="button primary" disabled={busy||!active.survey} onClick={()=>void mutate('/trajectories',{survey_revision_id:active.survey?.id,base_revision_id:active.trajectory?.id??null,change_note:'Recalculate from selected saved source',...(active.trajectory&&active.survey&&JSON.stringify(active.trajectory.frame)===JSON.stringify(active.survey.frame)?{geometry:{...active.trajectory.input,survey_dataset_id:context.survey_source?.id}}:{})})}>Calculate and save trajectory</button>
      <details><summary>Save / import a source revision</summary><form onSubmit={saveSource}>
        <label className="field-label">Source method<select value={mode} disabled={busy} onChange={e=>setMode(e.target.value)}><option value="authored">Authored SI stations</option><option value="csv">Original CSV import</option><option value="adopt">Explicitly adopt a project source</option></select></label>
        <label className="field-label">Evidence origin<select value={evidence} onChange={e=>setEvidence(e.target.value)}>{['synthetic',...(role==='actual'?[]:['authored_design']),...(mode==='authored'?[]:['unqualified_observation'])].map(s=><option key={s}>{s}</option>)}</select></label>
        {mode==='authored'?<label className="field-label">Authored stations JSON · MD metres, inclination and azimuth radians<textarea aria-label="Authored survey stations JSON" rows={10} value={stationText} onChange={e=>setStationText(e.target.value)}/></label>:mode==='csv'?<label className="field-label">Original survey CSV<input aria-label="Original survey CSV" type="file" accept=".csv" required onChange={e=>setFile(e.target.files?.[0]??null)}/><span>Headers: md[m], inclination[deg], azimuth[deg]. MD starts at 0 and strictly increases.</span></label>:<label className="field-label">Project source<select required value={dataset} onChange={e=>setDataset(e.target.value)}><option value="">Choose source</option>{datasets.filter(d=>d.kind==='survey').map(d=><option key={d.id} value={d.id}>{d.filename} · {d.id.slice(0,8)}</option>)}</select></label>}
        <div className="lab-fields"><label className="field-label">Declared coordinate frame / CRS<input required minLength={3} maxLength={200} value={frame.coordinate_reference} onChange={e=>setFrame({...frame,coordinate_reference:e.target.value})}/></label>{(['wellhead_north_m','wellhead_east_m','wellhead_elevation_m'] as const).map(k=><label className="field-label" key={k}>{k.replaceAll('_',' ')} · metres<input required type="number" step="any" value={frame[k]} onChange={e=>setFrame({...frame,[k]:Number(e.target.value)})}/></label>)}</div>
        <p>Depth datum {datum} · {northReference} north · elevation is positive up. The declared frame must be shared explicitly with any compared offset. No coordinate transformation is inferred.</p>
        <label className="field-label">Source quality / applicability note<input required minLength={3} maxLength={300} value={quality} onChange={e=>setQuality(e.target.value)}/></label>
        <label className="field-label">Tool and acquisition metadata JSON<textarea rows={3} value={toolMetadata} onChange={e=>setToolMetadata(e.target.value)}/></label>
        <label className="field-label">Revision change note<input required minLength={3} maxLength={300} value={note} onChange={e=>setNote(e.target.value)}/></label><button className="button primary" disabled={busy}>Save survey revision</button>
      </form></details>
      <label className="field-label">Inspect a historical revision · does not change active data<select value={historyId} onChange={e=>setHistoryId(e.target.value)}><option value="">Choose preserved revision</option>{context.revisions.map(r=><option key={r.id} value={r.id}>{r.trajectory_type} · {r.kind} r{r.revision_no} · {r.id.slice(0,8)}</option>)}</select></label>
      {historical&&<details open><summary>Historical evidence · {historical.freshness.stale?'stale dependencies':'unchanged dependencies'}</summary><pre>{JSON.stringify(historical,null,2)}</pre></details>}
    </div>
    <div className="panel"><h2>Planned / actual / scenario comparison</h2><p>Saved kernel samples in the declared coordinate frame; the geometry is never recalculated by the chart.</p><div className="heading-actions">{roles.map(r=><label key={r}><input type="checkbox" checked={visibility[r]} onChange={e=>setVisibility({...visibility,[r]:e.target.checked})}/>{r}</label>)}</div>{roles.filter(r=>visibility[r]&&context.comparison_state[r]).map(r=><p key={r}>{r} r{context.comparison_state[r]?.revision_no} · {context.comparison_state[r]?.revision_id.slice(0,8)} · {context.comparison_state[r]?.stale?'STALE source dependency':'bound to saved source'}</p>)}<Comparison revisions={comparisons.filter(r=>visibility[r.trajectory_type])} selectedMD={selectedMD}/><p>Blue: planned · orange: actual · teal: scenario</p><div className="heading-actions">{active.trajectory?.trajectory_type&&[...new Set(active.trajectory.result.samples.map(p=>p.md_m))].filter((_,i)=>i%Math.max(1,Math.ceil(active.trajectory!.result.samples.length/12))===0).map(md=><button className="text-button" key={md} onClick={()=>onSelectMD(md)}>Select MD {fmt(md)} m</button>)}</div></div>
    <div className="panel"><h2>Saved survey uncertainty</h2><p>The pinned model requires declared tool applicability and geomagnetic evidence. Missing inputs are saved as withheld. Covariance diagnostics do not establish field qualification.</p><label className="field-label">Uncertainty metadata JSON<textarea aria-label="Wellbore uncertainty metadata JSON" rows={5} value={uncertaintyMetadata} onChange={e=>setUncertaintyMetadata(e.target.value)}/></label><button className="button primary" disabled={busy||!active.trajectory} onClick={()=>{try{void mutate('/uncertainty',{trajectory_revision_id:active.trajectory?.id,metadata:object(uncertaintyMetadata)});}catch(e){onError((e as Error).message);}}}>Calculate and save uncertainty</button>{diagnostic('uncertainty')}</div>
    <div className="panel"><h2>Saved offset proximity</h2><p>Compare an explicitly selected offset revision in the same declared frame. Distance is a research diagnostic. This kernel does not calculate covariance separation factors or correlated errors; separation and drilling clearance are withheld.</p><div className="lab-fields"><label className="field-label">Offset wellbore<select value={offsetId} onChange={e=>setOffsetId(e.target.value)}><option value="">Choose offset</option>{offsets.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label className="field-label">Offset trajectory revision<select value={offsetRevision} onChange={e=>setOffsetRevision(e.target.value)}><option value="">Choose preserved trajectory</option>{offsetTrajectories.map(t=><option key={t.id} value={t.id}>{t.trajectory_type} r{t.revision_no} · {t.id.slice(0,8)}</option>)}</select></label><label className="field-label">Correlation assumption<select value={correlation} onChange={e=>setCorrelation(e.target.value)}>{['independent','systematic_geomagnetic','fully_correlated'].map(k=><option key={k} disabled={k!=='independent'}>{k}{k==='independent'?'':' (not implemented)'}</option>)}</select></label></div><label className="field-label">Geomagnetic evidence JSON · recorded metadata; separation factor unavailable<textarea rows={4} value={geomagnetic} onChange={e=>setGeomagnetic(e.target.value)}/></label><button className="button primary" disabled={busy||!active.trajectory||!offsetRevision} onClick={()=>{try{void mutate('/anticollision/calculate',{trajectory_revision_id:active.trajectory?.id,offset_wellbore_id:offsetId,offset_trajectory_revision_id:offsetRevision,geomagnetic:object(geomagnetic),correlation_mode:correlation});}catch(e){onError((e as Error).message);}}}>Calculate and save offset proximity</button>{diagnostic('proximity')}</div>
  </>;
}

function Comparison({revisions,selectedMD}:{revisions:SavedTrajectory[];selectedMD:number|null}){
  if(!revisions.length)return <p>No selected role has a saved trajectory.</p>;
  if(revisions.some(r=>['datum','coordinate_reference','north_reference'].some(k=>r.frame[k as keyof Frame]!==revisions[0].frame[k as keyof Frame])))return <p className="alert warning">Comparison withheld: selected trajectories declare different frames, datums or north references.</p>;
  const points=revisions.flatMap(r=>r.result.samples);
  const colors={planned:'#0B3D91',actual:'#F97316',scenario:'#0F766E'};
  return <div className="form-columns">{(['plan','section'] as const).map(view=>{
    const raw=(p:Revision['result']['samples'][number])=>view==='plan'?[p.east_m,-p.north_m]:[p.north_m,-p.elevation_m];
    const xs=points.map(p=>raw(p)[0]),ys=points.map(p=>raw(p)[1]);const x0=Math.min(...xs),y0=Math.min(...ys);
    const scale=Math.min(450/Math.max(1,Math.max(...xs)-x0),270/Math.max(1,Math.max(...ys)-y0));const xy=(p:typeof points[number])=>{const [x,y]=raw(p);return [50+(x-x0)*scale,25+(y-y0)*scale];};
    return <div key={view}><h3>{view==='plan'?'Plan · North up':'Section · North / vertical down'}</h3><svg viewBox="0 0 560 345" className="engineering-plan" role="img" aria-label={'Saved role comparison '+view+' with equal spatial scale'}>{revisions.map(r=>{const selected=selectedMD===null?null:r.result.samples.reduce((a,b)=>Math.abs(b.md_m-selectedMD)<Math.abs(a.md_m-selectedMD)?b:a);return <g key={r.id}><path d={r.result.samples.map((p,i)=>(i?'L':'M')+xy(p).join(',')).join(' ')} fill="none" stroke={colors[r.trajectory_type]} strokeWidth="3"/>{selected&&<circle cx={xy(selected)[0]} cy={xy(selected)[1]} r="5" fill={colors[r.trajectory_type]}/>}</g>;})}<text x="50" y="320">{view==='plan'?'East / North':'North / vertical relative to datum'} (m) · equal scale</text><text x="50" y="339">Origin {fmt(x0)}, {fmt(view==='plan'?-y0:y0)} m · {fmt(100/scale)} m per 100 SVG units</text></svg></div>;
  })}</div>;
}
