import {Component,lazy,Suspense,useMemo,useState,type ReactNode} from 'react';
import type {Revision} from './GeometryWorkspace';
import {buildScenePath,canonicalNEV,canonicalDistance,nearestSampleIndex,type SceneFrame,type StationIdentity} from './sceneModel';
const SceneCanvas=lazy(()=>import('./EngineeringSceneCanvas'));
type Props={revision:Revision|null;activeSurveyID?:string;datum:string;northReference:string;selectedMD:number|null;surveyMDs?:number[];onSelectMD:(md:number)=>void;onGeometryPage:()=>void};
class RendererBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true};}render(){return this.state.failed?<p role="alert">The 3D renderer could not start. Saved coordinates remain available below.</p>:this.props.children;}}
export function Well3DWorkspace(props:Props){if(!props.revision)return <div className="panel"><h2>No saved engineering geometry</h2><p>Import a survey and save a geometry revision before opening this model.</p><button className="button primary" onClick={props.onGeometryPage}>Open well geometry</button></div>;return <SavedScene key={props.revision.id} {...props} revision={props.revision}/>;}
function SavedScene({revision,activeSurveyID,datum,northReference,selectedMD,surveyMDs,onSelectMD,onGeometryPage}:Props & {revision:Revision}){
  const [exaggeration,setExaggeration]=useState(1),[unit,setUnit]=useState('m'),[formations,setFormations]=useState(true),[casings,setCasings]=useState(true),[fitRequest,setFitRequest]=useState(0),[fitSelected,setFitSelected]=useState(false),[rendererState,setRendererState]=useState('Starting WebGL'),[measureFrom,setMeasureFrom]=useState<number|null>(null);
  const frame:SceneFrame=useMemo(()=>({...revision.input,north_reference:northReference}),[revision,northReference]);
  const transform=useMemo(()=>({origin:[frame.wellhead_north_m,frame.wellhead_east_m,-frame.wellhead_elevation_m] as [number,number,number],metresToDisplay:unit==='m'?1:1/.3048,verticalExaggeration:exaggeration}),[frame,unit,exaggeration]);
  const result=useMemo(()=>{try{return {path:buildScenePath({id:revision.id,sha256:revision.sha256,wellbore_id:revision.wellbore_id,trajectory_type:revision.trajectory_type,frame,samples:revision.result.samples,surveyMDs},transform,frame),error:null};}catch(error){return {path:null,error:(error as Error).message};}},[revision,frame,transform,surveyMDs]);
  const pick=(identity:StationIdentity)=>onSelectMD(identity.md_m),index=selectedMD===null||!result.path?null:nearestSampleIndex(revision.result.samples,selectedMD),sample=index===null?null:revision.result.samples[index];
  const windowStart=Math.max(0,(index??0)-40),visible=revision.result.samples.slice(windowStart,windowStart+100),measure=sample&&measureFrom!==null?canonicalDistance(canonicalNEV(revision.result.samples[measureFrom],frame),canonicalNEV(sample,frame)):null;
  return <div className="panel"><div className="panel-heading"><div><h2>3D well engineering · saved revision</h2><p>Geometry {revision.id.slice(0,8)} · source hash {revision.sha256.slice(0,16)}… · {revision.trajectory_type??'legacy project geometry'}</p></div><button className="button secondary" onClick={onGeometryPage}>Edit geometry</button></div>
    {activeSurveyID!==revision.input.survey_dataset_id&&<p className="alert warning">Historical geometry: coordinates remain bound to the earlier survey. Current source selection does not change this saved revision.</p>}
    <p>Frame: {frame.coordinate_reference} · Datum: {datum} · {northReference} north · elevation reference: declared wellhead {frame.wellhead_elevation_m} m · local display origin N {frame.wellhead_north_m}, E {frame.wellhead_east_m}, elevation {frame.wellhead_elevation_m} m.</p>
    <p>Grid convergence: {northReference==='grid'?'not supplied; no grid-to-true conversion is applied':'not applied in the declared true-north frame'}. Canonical coordinates are metres; TVD is positive down. Local/unreferenced frames remain unreferenced.</p>
    <div className="scene-controls"><label>Display units<select aria-label="3D display units" value={unit} onChange={event=>setUnit(event.target.value)}><option value="m">Metres</option><option value="ft">Feet</option></select></label><label>Vertical exaggeration<input aria-label="3D vertical exaggeration" type="number" min=".1" max="10" step=".1" value={exaggeration} onChange={event=>{const value=Number(event.target.value);if(value>=.1&&value<=10)setExaggeration(value);}}/></label><label><input type="checkbox" checked={formations} onChange={event=>setFormations(event.target.checked)}/>Interpreted formation tops</label><label><input type="checkbox" checked={casings} onChange={event=>setCasings(event.target.checked)}/>Casing centre lines</label><button className="button secondary" onClick={()=>{setFitSelected(false);setFitRequest(value=>value+1);}}>Fit well</button><button className="button secondary" disabled={!sample} onClick={()=>{setFitSelected(true);setFitRequest(value=>value+1);}}>Fit selected</button></div>
    {result.error?<p role="alert" className="alert warning">Rendering withheld: {result.error}</p>:result.path&&<RendererBoundary><Suspense fallback={<p>Loading the 3D renderer…</p>}><SceneCanvas path={result.path} revision={revision} transform={transform} selectedMD={selectedMD} onPick={pick} fitRequest={fitRequest} fitSelected={fitSelected} formations={formations} casings={casings} onReady={()=>setRendererState('WebGL ready')} onLost={()=>setRendererState('WebGL context lost; reload this view to recover')}/></Suspense></RendererBoundary>}
    <p role="status">{rendererState} · axes +X East, +Y elevation, −Z North · display {unit}, vertical exaggeration ×{exaggeration}. Display transforms do not change engineering coordinates.</p>
    {sample&&<div><p>Selected MD {selectedMD} m · nearest saved sample MD {sample.md_m} m · N {sample.north_m.toFixed(3)} m · E {sample.east_m.toFixed(3)} m · TVD {sample.tvd_m.toFixed(3)} m</p><button className="button secondary" onClick={()=>setMeasureFrom(index)}>Set distance origin at selected sample</button>{measure!==null&&<p>Canonical straight-line distance between saved samples: {measure.toFixed(3)} m. This is a geometric measurement, not drilling clearance.</p>}</div>}
    <details open><summary>Saved coordinates and keyboard-accessible station selection</summary><p>Showing {windowStart+1}–{Math.min(windowStart+100,revision.result.samples.length)} of {revision.result.samples.length} saved kernel samples around selection. Original survey stations are identified separately; intermediate samples are not observations.</p><div className="table-scroll"><table><thead><tr><th>MD (m)</th><th>North (m)</th><th>East (m)</th><th>TVD (m)</th><th>Identity</th><th>Select</th></tr></thead><tbody>{visible.map((point,i)=><tr key={point.md_m}><td>{point.md_m}</td><td>{point.north_m.toFixed(3)}</td><td>{point.east_m.toFixed(3)}</td><td>{point.tvd_m.toFixed(3)}</td><td>{result.path?.stations[windowStart+i].surveyStation?'Survey station':'Saved geometry sample'}</td><td><button className="text-button" aria-label={'Select 3D MD '+point.md_m+' m'} onClick={()=>onSelectMD(point.md_m)}>Select</button></td></tr>)}</tbody></table></div></details>
    <p className="muted">Formation planes are illustrative flat interpreted tops around the wellhead, not surveyed regional surfaces. Casing centre lines do not depict actual diameters. Planned/actual/offset cohorts, reference-bound targets/BHA, covariance meshes, clipping, section planes and representative WebGL load validation remain open phase-5 work.</p>
  </div>;
}
