"""Drafts for audited Modules 12–17; generated values are never field measurements."""
def late_template(model,revision,origin):
    td=revision["result"]["total_depth_md_m"]
    base={"study_name":("Synthetic " if origin=="synthetic" else "Draft ")+model+" scenario","geometry_revision_id":revision["id"],"depth_datum":revision["input"]["datum"],"evidence_state":"synthetic" if origin=="synthetic" else "unknown","source_note":"Generated research assumptions; no instrument, material or field qualification" if origin=="synthetic" else "Replace draft assumptions with traceable evidence"}
    if model=="dynamics":
        return {**base,"top_md_m":0.,"bottom_md_m":min(td,50.),"outside_diameter_m":.127,"inside_diameter_m":.108,"material_density_kg_m3":7850.,"young_modulus_pa":207e9,"poisson_ratio":.3,"boundary":"cantilever_reduced","configuration_note":"Uniform cantilever generalized-coordinate example; no virtual downhole diagnosis","damping_ratio":.03,"axial_torsional_coupling":.1,"axial_lateral_coupling":.05,"torsional_lateral_coupling":.05,"bit_axial_stiffness_n_per_m":10000.,"lateral_clearance_m":.005,"contact_stiffness_n_per_m":100000.,"axial_force_amplitude_n":1000.,"torque_amplitude_nm":100.,"lateral_force_amplitude_n":100.,"excitation_hz":8.,"duration_s":.5,"time_step_s":.0005,"refinement_relative_tolerance":.01,"sensors":[]}
    if model=="bit-condition":
        runs=[]
        for i,(hours,term) in enumerate([(10.,"confirmed_failure"),(20.,"planned_trip"),(30.,"confirmed_failure"),(40.,"planned_trip")]):
            runs.append({"run_id":"Example-"+str(i+1),"well":"Synthetic independent well "+str(i+1),"bit_serial":"Synthetic bit "+str(i+1),"bit_family":"Synthetic PDC family","formation":"Synthetic formation","completed_at":"2026-01-0"+str(i+1)+"T12:00:00Z","available_at":"2026-01-0"+str(i+1)+"T13:00:00Z","drilling_hours":hours,"drilled_m":hours*10,"recovered":True,"termination":term,"inspection_grade":"Synthetic inspection record","inspection_note":"Generated illustrative recovered-bit evidence","photograph_reference":None,"mechanical_energy_j":None,"energy_basis":"not_supplied","evidence_note":"Manufactured run record; no fitted field accuracy"})
        return {**base,"cutoff_at":"2026-01-05T00:00:00Z","bit_family":"Synthetic PDC family","formation":"Synthetic formation","current_drilling_hours":5.,"horizon_hours":10.,"immediate_trip_cost":10000.,"unplanned_failure_cost":50000.,"continuation_cost_per_hour":100.,"cost_currency":"USD","cost_note":"Synthetic costs; no continuation/trip authorization","runs":runs}
    if model=="wear-fatigue":
        casings=revision["input"]["casings"];c=casings[0] if casings else None
        return {**base,"casing_name":c["name"] if c else "Save a casing record first","geometry_assumption":"uniform_wall_loss","wear_coefficient_m2_n":1e-13,"wear_coefficient_relative_delta":.25,"wear_material_fluid_note":"Generated wear coefficient in m²/N; no material/fluid qualification","contact_patch_area_m2":1.,"initial_minimum_wall_m":c["minimum_wall_m"] if c else .01,"unobserved_exposure":False,"exposures":[{"name":"Synthetic contact window","normal_force_n":10000.,"sliding_distance_m":100000.,"duration_s":1000.,"evidence_note":"Generated constant contact exposure"}],"fatigue_material_note":"Generated zero-mean fatigue spectrum; not a material certificate","fatigue_curve":[{"stress_amplitude_pa":50e6,"failure_cycles":1e7},{"stress_amplitude_pa":100e6,"failure_cycles":1e6},{"stress_amplitude_pa":200e6,"failure_cycles":1e5}],"cycle_exposures":[{"stress_amplitude_pa":100e6,"mean_stress_pa":0.,"cycles":10000.,"evidence_note":"Synthetic cycle count; no inferred unmeasured cycles"}],"internal_gauge_pa":5e6,"external_gauge_pa":0.,"observed_minimum_wall_m":None,"inspection_uncertainty_m":.0001,"inspection_note":None}
    if model=="anomaly":
        samples=[{"time_s":float(i),"inlet_kg_s":12. if 5<=i<=14 else 10.,"outlet_kg_s":10.,"transfer_into_kg_s":0.,"contained_mass_kg":10000.,"pump_on":True,"operation":"circulating","quality":"accepted"} for i in range(21)]
        return {**base,"control_volume_note":"Manufactured fixed-mass control volume; inlet/outlet/known transfer all use this boundary","instrument_calibration_note":"Synthetic samples; no meter calibration claimed","maximum_gap_s":2.,"meter_allowance_kg_s":.1,"residual_threshold_kg_s":1.,"persistence_s":3.,"samples":samples,"adjudicated_events":[{"name":"Injected balance anomaly","onset_s":5.,"end_s":15.,"baseline_alarm_s":10.,"evidence_note":"Synthetic independently specified injection"}],"adjudication_note":"Generated event reference; not a field well-control corpus"}
    if model=="gas-phase":
        return {**base,"mode":"native_binary_flash","fluid_system":"characterized_nonpolar_binary","characterization_note":"Rounded methane/ethane critical properties for EOS verification; not drilling-mud characterization","components":[{"name":"Methane example","critical_temperature_k":190.56,"critical_pressure_pa":4599200.,"acentric_factor":.011,"mole_fraction":.5},{"name":"Ethane example","critical_temperature_k":305.32,"critical_pressure_pa":4872000.,"acentric_factor":.099,"mole_fraction":.5}],"binary_interaction":0.,"absolute_pressure_pa":1e6,"temperature_k":200.,"external_model_reference":None,"external_review_state":"unknown","external_review_note":None,"external_points":[],"total_gas_inventory_mol":10.,"initial_dissolved_gas_mol":8.,"mass_transfer_time_s":10.,"replay_step_s":1.,"balance_tolerance_mol":.01}
    if model=="supervision":
        return {**base,"authority_mode":"simulation_lease","plant_note":"Generated first-order pressure plant, isolated software simulation only","target_pressure_pa":22e6,"minimum_simulated_pressure_pa":18e6,"maximum_simulated_pressure_pa":24e6,"pressure_envelope_note":"Synthetic scenario pressure bounds, not rig-approved protection","initial_pressure_pa":20e6,"plant_zero_pressure_pa":20e6,"plant_gain_pa":5e6,"plant_time_constant_s":2.,"proportional_per_pa":1e-7,"integral_per_pa_s":2e-8,"derivative_s_per_pa":0.,"actuator_minimum":0.,"actuator_maximum":1.,"actuator_rate_per_s":.2,"transport_delay_s":.2,"request_ttl_s":3.,"simulation_lease_expires_s":30.,"maximum_requests_per_s":100.,"manual_override_position":.3,"duration_s":20.,"time_step_s":.1,"refinement_pressure_tolerance_pa":100000.,"faults":[],"request_examples":[]}
    raise ValueError("Unknown late-module template.")
