import {spawnSync} from 'node:child_process';
import {mkdirSync} from 'node:fs';
import assert from 'node:assert/strict';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {BufferAttribute,BufferGeometry,PerspectiveCamera,Points,PointsMaterial,Raycaster,Vector2,Vector3} from 'three';
mkdirSync('build/scene-tests',{recursive:true});
const compile=spawnSync(process.execPath,['node_modules/typescript/bin/tsc','apps/desktop/src/sceneModel.ts','--target','ES2022','--module','ES2022','--moduleResolution','Bundler','--skipLibCheck','--outDir','build/scene-tests'],{stdio:'inherit'});
if(compile.status!==0)process.exit(compile.status??1);
const {canvasPointer,closestRayVertex,buildScenePath,canonicalNEV,displayPosition,undisplayPosition,canonicalDistance,stationAtVertex,nearestSampleIndex}=await import(pathToFileURL(resolve('build/scene-tests/sceneModel.js')));
const frame={coordinate_reference:'Declared shared local frame',datum:'RKB',north_reference:'true',wellhead_north_m:1e8,wellhead_east_m:1e8,wellhead_elevation_m:30};
const samples=[{md_m:0,north_m:0,east_m:0,tvd_m:0,elevation_m:30},{md_m:10,north_m:3,east_m:4,tvd_m:5,elevation_m:25},{md_m:20,north_m:6,east_m:8,tvd_m:10,elevation_m:20}];
const source={id:'saved-revision',sha256:'original-hash',wellbore_id:'mainbore',trajectory_type:'actual',frame,samples,surveyMDs:[0,20]};
const original=JSON.stringify(source),transform={origin:[1e8,1e8,-30],metresToDisplay:1,verticalExaggeration:1};
let count=0;function check(name,action){action();count++;console.log('PASS '+name);}
check('saved kernel axes and origin, with no double origin',()=>assert.deepEqual(Array.from(buildScenePath(source,transform,frame).positions),[0,0,0,4,-5,-3,8,-10,-6]));
check('float32 receives local deltas, retaining small values at large origins',()=>assert.equal(buildScenePath(source,transform,frame).positions[3],4));
check('vertical exaggeration preserves original canonical geometry',()=>{assert.deepEqual(displayPosition(canonicalNEV(samples[1],frame),{...transform,verticalExaggeration:3}),[4,-15,-3]);assert.equal(JSON.stringify(source),original);});
check('display-unit conversion scales all axes equally',()=>{const p=displayPosition(canonicalNEV(samples[1],frame),{...transform,metresToDisplay:1/.3048});assert.ok(Math.abs(p[0]-4/.3048)<1e-10);assert.ok(Math.abs(p[1]+5/.3048)<1e-10);});
check('display transform round-trip',()=>{const t={...transform,metresToDisplay:1/.3048,verticalExaggeration:2};const canonical=canonicalNEV(samples[1],frame);assert.deepEqual(undisplayPosition(displayPosition(canonical,t),t),canonical);});
check('measurement uses canonical metres independent of exaggerated display',()=>assert.equal(canonicalDistance(canonicalNEV(samples[0],frame),canonicalNEV(samples[1],frame)),Math.sqrt(50)));
check('picked entity binds exact saved revision, source hash, role and MD',()=>assert.deepEqual(stationAtVertex(buildScenePath(source,transform,frame),2),{revisionId:'saved-revision',revisionHash:'original-hash',wellboreId:'mainbore',role:'actual',md_m:20,sampleIndex:2,surveyStation:true}));
check('kernel display samples are distinct from original survey stations',()=>assert.equal(stationAtVertex(buildScenePath(source,transform,frame),1).surveyStation,false));
check('nearest selection handles ties and out-of-range MD explicitly',()=>{assert.equal(nearestSampleIndex(samples,15),1);assert.equal(nearestSampleIndex(samples,100),2);assert.equal(nearestSampleIndex(samples,-1),0);});
check('foreign coordinate frame is withheld',()=>assert.throws(()=>buildScenePath({...source,frame:{...frame,coordinate_reference:'Other CRS'}},transform,frame),/shared frame/));
check('foreign datum and north reference are withheld',()=>{assert.throws(()=>buildScenePath({...source,frame:{...frame,datum:'MSL'}},transform,frame));assert.throws(()=>buildScenePath({...source,frame:{...frame,north_reference:'grid'}},transform,frame));});
check('missing frame identity is withheld',()=>assert.throws(()=>buildScenePath({...source,frame:{...frame,coordinate_reference:''}},transform,frame)));
check('non-finite geometry is withheld',()=>assert.throws(()=>buildScenePath({...source,samples:[{...samples[0],east_m:NaN}]},transform,frame)));
check('inconsistent reference or elevation values are withheld',()=>{assert.throws(()=>canonicalNEV({...samples[1],reference_north_m:2},frame));assert.throws(()=>canonicalNEV({...samples[1],elevation_m:1},frame));});
check('duplicate or decreasing MD is withheld',()=>assert.throws(()=>buildScenePath({...source,samples:[samples[1],samples[0]]},transform,frame)));
check('invalid pick cannot alias another station',()=>{assert.throws(()=>stationAtVertex(buildScenePath(source,transform,frame),-1));assert.throws(()=>stationAtVertex(buildScenePath(source,transform,frame),1.5));});
check('canvas client coordinates account for offset and scrolling',()=>{assert.deepEqual(canvasPointer(350,200,{left:100,top:100,width:500,height:200}),[0,0]);assert.deepEqual(canvasPointer(250,0,{left:0,top:-100,width:500,height:200}),[0,0]);});
check('CSS coordinates do not use drawing-buffer/device-pixel units',()=>assert.deepEqual(canvasPointer(1000,700,{left:500,top:400,width:1000,height:600}),[0,0]));
check('outside, hidden or invalid canvases cannot produce a pick',()=>{assert.equal(canvasPointer(0,0,{left:10,top:10,width:100,height:100}),null);assert.equal(canvasPointer(10,10,{left:0,top:0,width:0,height:100}),null);assert.equal(canvasPointer(NaN,10,{left:0,top:0,width:100,height:100}),null);});
check('nearest ray point wins over nearer-camera neighbours',()=>assert.equal(closestRayVertex([{index:0,distanceToRay:4,distance:1},{index:1,distanceToRay:.1,distance:10}]),1));
check('invalid ray intersections cannot alias a vertex',()=>assert.equal(closestRayVertex([{index:-1,distanceToRay:0,distance:1},{index:1,distanceToRay:NaN,distance:1}]),null));
check('actual Three.js raycast returns original source identity after offset and exaggeration',()=>{
  const t={...transform,metresToDisplay:1/.3048,verticalExaggeration:2},path=buildScenePath(source,t,frame);
  const geometry=new BufferGeometry().setAttribute('position',new BufferAttribute(path.positions,3)),material=new PointsMaterial(),points=new Points(geometry,material);
  points.updateMatrixWorld(true);const camera=new PerspectiveCamera(50,2,.01,1000);camera.position.set(70,30,60);camera.lookAt(new Vector3(10,-20,-10));camera.updateMatrixWorld(true);
  const projected=new Vector3().fromArray(path.positions,3).project(camera),rect={left:250,top:180,width:800,height:400};
  const pointer=canvasPointer(rect.left+(projected.x+1)*rect.width/2,rect.top+(1-projected.y)*rect.height/2,rect);assert.ok(pointer);
  const ray=new Raycaster();ray.params.Points.threshold=2;ray.setFromCamera(new Vector2(...pointer),camera);
  const vertex=closestRayVertex(ray.intersectObject(points));assert.equal(vertex,1);assert.equal(stationAtVertex(path,vertex).md_m,10);assert.equal(stationAtVertex(path,vertex).revisionHash,source.sha256);geometry.dispose();material.dispose();
});
check('renderer processes 100k samples without spread-argument overflow',()=>{const many=Array.from({length:100000},(_,i)=>({...samples[0],md_m:i,tvd_m:i,elevation_m:30-i}));const p=buildScenePath({...source,samples:many},transform,frame);assert.equal(p.positions.length,300000);assert.equal(p.bounds.min[1],-99999);});
console.log(`${count} scene coordinate and identity checks passed.`);
